INSERT INTO Products (ProductName, Brand, Model, SKU, ProductCategory, Gender,
 Price, Material, SubCategory, Surface, SupportType, Cushioning, Traction, WeightGrams, 
 IsWaterproof, Description) 
 VALUES
('Nike Pegasus 40','Nike','Pegasus 40','NK-PEG40-001','Running','Men',5500,'Mesh','Daily Running','Road','Neutral','Medium','Medium',288,FALSE,'Everyday neutral running shoe.'),
('Nike ZoomX Vaporfly 3','Nike','Vaporfly 3','NK-VPF3-001','Running','Unisex',12500,'Flyknit','Racing','Road','Neutral','High','Medium',198,FALSE,'Elite marathon racing shoe.'),
('Adidas Ultraboost Light','Adidas','Ultraboost Light','AD-UBL-001','Running','Men',7500,'Primeknit','Daily Running','Road','Neutral','High','High',299,FALSE,'Premium cushioned running shoe.'),
('Adidas Adizero Adios Pro 3','Adidas','Adios Pro 3','AD-AAP3-001','Running','Unisex',11500,'Mesh','Racing','Road','Neutral','High','Medium',215,FALSE,'Carbon-plated racing shoe.'),
('ASICS Gel-Nimbus 26','ASICS','Gel-Nimbus 26','AS-NIM26-001','Running','Women',8200,'Mesh','Daily Running','Road','Neutral','Maximum','High',290,FALSE,'Max cushion long distance shoe.'),
('ASICS Novablast 4','ASICS','Novablast 4','AS-NOV4-001','Running','Men',6800,'Mesh','Daily Running','Road','Neutral','High','Medium',260,FALSE,'Bouncy daily trainer.'),
('Brooks Ghost 15','Brooks','Ghost 15','BK-GHO15-001','Running','Women',6500,'Mesh','Daily Running','Road','Neutral','Medium','Medium',258,FALSE,'Reliable daily running shoe.'),
('Brooks Glycerin 21','Brooks','Glycerin 21','BK-GLY21-001','Running','Men',7800,'Mesh','Daily Running','Road','Neutral','Maximum','High',289,FALSE,'Ultra-soft cushioning running shoe.'),
('New Balance 1080v13','New Balance','1080v13','NB-1080V13-001','Running','Men',8500,'Knit','Daily Running','Road','Neutral','Maximum','Medium',262,FALSE,'Premium cushioned daily runner.'),
('New Balance SuperComp Elite v4','New Balance','SC Elite v4','NB-SCE4-001','Running','Unisex',12000,'Mesh','Racing','Road','Neutral','High','Low',235,FALSE,'Race day carbon shoe.'),
('HOKA Clifton 9','HOKA','Clifton 9','HK-CLF9-001','Running','Women',7200,'Mesh','Daily Running','Road','Neutral','High','Medium',248,FALSE,'Lightweight max cushion shoe.'),
('HOKA Bondi 8','HOKA','Bondi 8','HK-BND8-001','Running','Men',7800,'Mesh','Recovery','Road','Neutral','Maximum','Medium',307,FALSE,'Maximum comfort and protection.'),
('Puma Magnify Nitro 2','Puma','Magnify Nitro 2','PM-MGN2-001','Running','Men',6800,'Mesh','Daily Running','Road','Neutral','Maximum','High',274,FALSE,'Thick nitro foam cushioning.'),
('Puma Velocity Nitro 3','Puma','Velocity Nitro 3','PM-VLN3-001','Running','Women',5900,'Mesh','Daily Running','Road','Neutral','Medium','High',245,FALSE,'Versatile everyday trainer.'),
('Mizuno Wave Rider 27','Mizuno','Wave Rider 27','MZ-WVR27-001','Running','Men',6500,'Mesh','Daily Running','Road','Neutral','Medium','High',280,FALSE,'Smooth transition running shoe.'),
('Mizuno Wave Inspire 19','Mizuno','Wave Inspire 19','MZ-WVI19-001','Running','Women',6500,'Mesh','Daily Running','Road','Stability','Medium','High',245,FALSE,'Supportive stability runner.'),
('Skechers GO RUN Ride 11','Skechers','Ride 11','SK-GR11-001','Running','Men',5200,'Mesh','Daily Running','Road','Neutral','High','Medium',238,FALSE,'Hyper burst cushioned runner.'),
('Skechers Max Road 6','Skechers','Max Road 6','SK-MXR6-001','Running','Unisex',5800,'Mesh','Long Distance','Road','Neutral','Maximum','High',285,FALSE,'Long distance max cushion.'),
('UA Flow Velociti Wind 2','Under Armour','Velociti Wind 2','UA-FVW2-001','Running','Men',6200,'Knit','Speed Training','Road','Neutral','Low','High',236,FALSE,'Rubberless fast running shoe.'),
('UA HOVR Machina 3','Under Armour','Machina 3','UA-HVM3-001','Running','Women',6400,'Mesh','Daily Running','Road','Neutral','Medium','Medium',269,FALSE,'Smart connected running shoe.'),
('Nike InfinityRN 4','Nike','InfinityRN 4','NK-INF4-001','Running','Men',7900,'Flyknit','Daily Running','Road','Stability','High','Medium',315,FALSE,'Supportive reactx foam runner.'),
('Nike Structure 25','Nike','Structure 25','NK-STR25-001','Running','Women',6200,'Mesh','Daily Running','Road','Stability','Medium','High',265,FALSE,'Classic stability running shoe.'),
('Adidas Boston 12','Adidas','Boston 12','AD-BST12-001','Running','Men',7400,'Mesh','Speed Training','Road','Neutral','Medium','Medium',255,FALSE,'Up-tempo training shoe.'),
('Adidas Supernova Rise','Adidas','Supernova Rise','AD-SNR-001','Running','Women',6500,'Mesh','Daily Running','Road','Neutral','Medium','Medium',243,FALSE,'Comfortable daily distance shoe.'),
('ASICS Gel-Cumulus 26','ASICS','Gel-Cumulus 26','AS-CUM26-001','Running','Men',6800,'Mesh','Daily Running','Road','Neutral','Medium','High',255,FALSE,'Soft everyday running shoe.'),
('ASICS Gel-Kayano 30','ASICS','Gel-Kayano 30','AS-KAY30-001','Running','Women',8500,'Knit','Daily Running','Road','Stability','High','High',263,FALSE,'Premium stability running shoe.'),
('Brooks Adrenaline GTS 23','Brooks','Adrenaline GTS 23','BK-ADR23-001','Running','Men',7200,'Mesh','Daily Running','Road','Stability','Medium','High',286,FALSE,'Go-to stability shoe.'),
('Brooks Hyperion Tempo','Brooks','Hyperion Tempo','BK-HYP-001','Running','Women',6800,'Woven','Speed Training','Road','Neutral','Low','Medium',190,FALSE,'Lightweight speed workout shoe.'),
('New Balance 880v14','New Balance','880v14','NB-880V14-001','Running','Men',6800,'Mesh','Daily Running','Road','Neutral','Medium','Medium',269,FALSE,'Workhorse daily running shoe.'),
('New Balance Rebel v4','New Balance','Rebel v4','NB-REB4-001','Running','Women',6900,'Mesh','Speed Training','Road','Neutral','Medium','Medium',196,FALSE,'Fast and responsive trainer.'),
('HOKA Mach 6','HOKA','Mach 6','HK-MCH6-001','Running','Men',7500,'Mesh','Speed Training','Road','Neutral','Medium','Low',232,FALSE,'Snappy everyday speed shoe.'),
('HOKA Arahi 7','HOKA','Arahi 7','HK-ARH7-001','Running','Women',7200,'Mesh','Daily Running','Road','Stability','Medium','Medium',228,FALSE,'Dynamic stability running shoe.'),
('Puma Deviate Nitro 2','Puma','Deviate Nitro 2','PM-DEV2-001','Running','Men',7900,'Mesh','Speed Training','Road','Neutral','High','High',260,FALSE,'Plated training running shoe.'),
('Puma ForeverRun Nitro','Puma','ForeverRun Nitro','PM-FRN-001','Running','Women',7500,'Mesh','Daily Running','Road','Stability','High','High',224,FALSE,'Stability with nitro foam.'),
('Mizuno Wave Sky 7','Mizuno','Wave Sky 7','MZ-WVS7-001','Running','Men',7800,'Knit','Daily Running','Road','Neutral','Maximum','High',300,FALSE,'Floating feel maximum cushion.'),
('Mizuno Wave Rebellion Pro','Mizuno','Rebellion Pro','MZ-WRP-001','Running','Unisex',11000,'Mesh','Racing','Road','Neutral','High','Low',215,FALSE,'Aggressive marathon racing shoe.'),
('Skechers GO RUN Razor 4','Skechers','Razor 4','SK-RZR4-001','Running','Men',6200,'Mesh','Speed Training','Road','Neutral','Medium','Medium',226,FALSE,'Fast and light trainer.'),
('Skechers Persistence','Skechers','Persistence','SK-PRS-001','Running','Women',5500,'Mesh','Daily Running','Road','Neutral','Medium','High',238,FALSE,'Carbon infused daily trainer.'),
('UA Charged Bandit 7','Under Armour','Bandit 7','UA-BND7-001','Running','Men',4500,'Mesh','Daily Running','Road','Neutral','Medium','High',255,FALSE,'Affordable comfortable runner.'),
('UA HOVR Sonic 6','Under Armour','Sonic 6','UA-SNC6-001','Running','Women',5800,'Mesh','Daily Running','Road','Neutral','Medium','Medium',238,FALSE,'Flexible distance running shoe.'),
('Nike Motiva','Nike','Motiva','NK-MTV-001','Walking','Women',4500,'Mesh','Walking','Road','Neutral','High','Medium',260,FALSE,'Smooth walking experience.'),
('Adidas Walk Cloud','Adidas','Walk Cloud','AD-WKC-001','Walking','Men',3900,'Mesh','Walking','Road','Neutral','Medium','Medium',280,FALSE,'Cloud-like walking comfort.'),
('ASICS Gel-Mission','ASICS','Gel-Mission','AS-MIS-001','Walking','Men',3600,'Synthetic','Walking','Road','Neutral','Medium','High',320,FALSE,'Durable walking shoe.'),
('New Balance 577','New Balance','577','NB-577-001','Walking','Women',4200,'Leather','Walking','Road','Stability','Medium','High',310,FALSE,'All day walking support.'),
('Skechers GO WALK 6','Skechers','GO WALK 6','SK-GW6-001','Walking','Men',4100,'Mesh','Walking','Road','Neutral','Medium','Medium',245,FALSE,'Slip-on walking comfort.'),
('Skechers Arch Fit Walk','Skechers','Arch Fit Walk','SK-AFW-001','Walking','Women',4800,'Mesh','Walking','Road','Arch Support','High','Medium',260,FALSE,'Podiatrist certified arch support.'),
('Brooks Addiction Walker 2','Brooks','Addiction Walker 2','BK-AW2-001','Walking','Men',6500,'Leather','Walking','Road','Motion Control','High','High',380,FALSE,'Maximum support leather walker.'),
('HOKA Transport GTX','HOKA','Transport GTX','HK-TRPG-001','Walking','Unisex',9500,'Mesh','Commuting','Mixed','Neutral','High','High',318,TRUE,'Waterproof daily commuter shoe.'),
('Puma Walk Lite','Puma','Walk Lite','PM-WKL-001','Walking','Women',3200,'Mesh','Walking','Road','Neutral','Low','Medium',210,FALSE,'Ultra lightweight walking shoe.'),
('UA Essential Walking','Under Armour','Essential','UA-ESW-001','Walking','Men',3800,'Mesh','Walking','Road','Neutral','Medium','Medium',255,FALSE,'Breathable all day walking.'),
('Nike Metcon 9','Nike','Metcon 9','NK-MTC9-002','Training','Men',7200,'Mesh','Gym','Indoor','Stability','Firm','Medium',360,FALSE,'Ultimate cross training shoe.'),
('Nike SuperRep Go 3','Nike','SuperRep Go 3','NK-SRG3-001','Training','Women',4900,'Flyknit','HIIT','Indoor','Neutral','Medium','Low',240,FALSE,'Lightweight HIIT workout shoe.'),
('Adidas Dropset 2','Adidas','Dropset 2','AD-DRP2-001','Training','Men',6800,'Mesh','Weightlifting','Indoor','Stability','Firm','Medium',370,FALSE,'Stable base for heavy lifts.'),
('Adidas Powerlift 5','Adidas','Powerlift 5','AD-PWL5-001','Training','Unisex',5800,'Canvas','Weightlifting','Indoor','Stability','Firm','High',400,FALSE,'Dedicated weightlifting shoe.'),
('Reebok Nano X3','Reebok','Nano X3','RB-NNX3-001','Training','Unisex',6900,'Flexweave','Gym','Indoor','Stability','Medium','Medium',340,FALSE,'Versatile crossfit trainer.'),
('Reebok Legacy Lifter III','Reebok','Legacy Lifter III','RB-LL3-001','Training','Men',9500,'Leather','Weightlifting','Indoor','Stability','Firm','High',450,FALSE,'Olympic weightlifting shoe.'),
('Under Armour TriBase Reign 5','Under Armour','TriBase Reign 5','UA-TBR5-001','Training','Men',6500,'Mesh','Gym','Indoor','Stability','Firm','Medium',330,FALSE,'Low to ground gym shoe.'),
('Under Armour Project Rock 6','Under Armour','Project Rock 6','UA-PR6-001','Training','Unisex',8200,'Knit','Gym','Indoor','Stability','Medium','High',350,FALSE,'Dwayne Johnson signature trainer.'),
('Puma PWRFrame TR 2','Puma','PWRFrame TR 2','PM-PWT2-001','Training','Women',4600,'Mesh','HIIT','Indoor','Neutral','Medium','Medium',270,FALSE,'Supportive cardio trainer.'),
('Puma Fuse 2.0','Puma','Fuse 2.0','PM-FUS2-001','Training','Men',5500,'Mesh','Gym','Indoor','Stability','Firm','High',340,FALSE,'Strength training shoe.'),
('Nike Air Force 1 07','Nike','Air Force 1','NK-AF107-001','Lifestyle','Unisex',6200,'Leather','Casual','Street','Neutral','Medium','Medium',430,FALSE,'Classic white sneaker.'),
('Nike Dunk Low','Nike','Dunk Low','NK-DNKL-001','Lifestyle','Unisex',6500,'Leather','Casual','Street','Neutral','Low','Medium',410,FALSE,'Iconic retro hoops shoe.'),
('Nike Air Max 90','Nike','Air Max 90','NK-AM90-001','Lifestyle','Men',7200,'Leather/Mesh','Casual','Street','Neutral','Medium','Medium',390,FALSE,'Classic visible air cushioning.'),
('Nike Air Max 270','Nike','Air Max 270','NK-AM270-001','Lifestyle','Women',7800,'Mesh','Casual','Street','Neutral','High','Medium',320,FALSE,'Large air heel unit.'),
('Nike Blazer Mid 77','Nike','Blazer Mid 77','NK-BLZ77-001','Lifestyle','Unisex',5800,'Leather','Casual','Street','Neutral','Low','Medium',420,FALSE,'Vintage mid-top sneaker.'),
('Adidas Stan Smith','Adidas','Stan Smith','AD-STM-001','Lifestyle','Unisex',5500,'Synthetic','Casual','Street','Neutral','Low','Medium',380,FALSE,'Clean classic tennis style.'),
('Adidas Superstar','Adidas','Superstar','AD-SPS-001','Lifestyle','Unisex',5500,'Leather','Casual','Street','Neutral','Low','Medium',400,FALSE,'Shell toe classic sneaker.'),
('Adidas Gazelle','Adidas','Gazelle','AD-GZL-001','Lifestyle','Unisex',5200,'Suede','Casual','Street','Neutral','Low','Medium',360,FALSE,'Retro suede sneaker.'),
('Adidas Samba OG','Adidas','Samba OG','AD-SMB-001','Lifestyle','Unisex',6200,'Leather','Casual','Street','Neutral','Low','Medium',350,FALSE,'Trending classic indoor football style.'),
('Adidas NMD_R1','Adidas','NMD_R1','AD-NMD1-001','Lifestyle','Men',7200,'Primeknit','Casual','Street','Neutral','Medium','Medium',290,FALSE,'Modern boost lifestyle shoe.'),
('New Balance 550','New Balance','550','NB-550-001','Lifestyle','Unisex',6800,'Leather','Casual','Street','Neutral','Medium','Medium',420,FALSE,'Retro basketball lifestyle shoe.'),
('New Balance 2002R','New Balance','2002R','NB-2002R-001','Lifestyle','Men',7500,'Suede/Mesh','Casual','Street','Neutral','Medium','Medium',370,FALSE,'Y2K running style sneaker.'),
('New Balance 9060','New Balance','9060','NB-9060-001','Lifestyle','Unisex',8500,'Suede/Mesh','Casual','Street','Neutral','High','Medium',410,FALSE,'Chunky futuristic lifestyle shoe.'),
('New Balance 990v6','New Balance','990v6','NB-990V6-001','Lifestyle','Men',10500,'Suede/Mesh','Casual','Street','Stability','Medium','High',380,FALSE,'Made in USA premium sneaker.'),
('Puma Suede Classic','Puma','Suede Classic','PM-SDC-001','Lifestyle','Unisex',4500,'Suede','Casual','Street','Neutral','Low','Medium',370,FALSE,'Timeless suede sneaker.'),
('Puma RS-X','Puma','RS-X','PM-RSX-001','Lifestyle','Unisex',5800,'Mesh/Synthetic','Casual','Street','Neutral','High','Medium',420,FALSE,'Chunky retro running style.'),
('ASICS GEL-Lyte III','ASICS','GEL-Lyte III','AS-GL3-001','Lifestyle','Unisex',6500,'Suede/Mesh','Casual','Street','Neutral','Medium','Medium',340,FALSE,'Split tongue heritage sneaker.'),
('Reebok Club C 85','Reebok','Club C 85','RB-CC85-001','Lifestyle','Unisex',4800,'Leather','Casual','Street','Neutral','Low','Medium',350,FALSE,'Vintage tennis lifestyle shoe.'),
('Converse Chuck 70','Converse','Chuck 70','CV-C70-001','Lifestyle','Unisex',4500,'Canvas','Casual','Street','Neutral','Medium','Medium',410,FALSE,'Premium canvas high top.'),
('Converse Jack Purcell','Converse','Jack Purcell','CV-JP-001','Lifestyle','Unisex',4200,'Canvas','Casual','Street','Neutral','Low','Medium',390,FALSE,'Classic smile toe sneaker.'),
('Vans Old Skool','Vans','Old Skool','VN-OS-002','Lifestyle','Unisex',4200,'Canvas/Suede','Casual','Street','Neutral','Low','Medium',390,FALSE,'Iconic sidestripe skate shoe.'),
('Vans Slip-On','Vans','Slip-On','VN-SLP-001','Lifestyle','Unisex',3800,'Canvas','Casual','Street','Neutral','Low','Low',350,FALSE,'Classic checkerboard slip on.'),
('Vans Sk8-Hi','Vans','Sk8-Hi','VN-SK8-001','Lifestyle','Unisex',4600,'Canvas/Suede','Casual','Street','Neutral','Low','Medium',420,FALSE,'High top skate classic.'),
('Nike Air Max Plus','Nike','Air Max Plus','NK-AMP-001','Lifestyle','Men',8500,'Mesh','Casual','Street','Neutral','High','Medium',380,FALSE,'Tuned air distinctive design.'),
('Nike Cortez','Nike','Cortez','NK-CRTZ-001','Lifestyle','Women',5200,'Leather','Casual','Street','Neutral','Low','Medium',310,FALSE,'Heritage running style.'),
('Adidas Campus 00s','Adidas','Campus 00s','AD-CMP00-001','Lifestyle','Unisex',5800,'Suede','Casual','Street','Neutral','Low','Medium',400,FALSE,'Chunky skate inspired retro.'),
('Adidas Forum Low','Adidas','Forum Low','AD-FRM-001','Lifestyle','Unisex',5500,'Leather','Casual','Street','Neutral','Medium','Medium',430,FALSE,'80s basketball lifestyle shoe.'),
('Adidas Ozelia','Adidas','Ozelia','AD-OZL-001','Lifestyle','Men',6500,'Textile','Casual','Street','Neutral','Medium','Medium',370,FALSE,'Futuristic chunky sneaker.'),
('New Balance 327','New Balance','327','NB-327-001','Lifestyle','Women',5800,'Nylon/Suede','Casual','Street','Neutral','Medium','Medium',310,FALSE,'70s inspired retro runner.'),
('New Balance 574 Core','New Balance','574 Core','NB-574C-001','Lifestyle','Unisex',5500,'Suede/Mesh','Casual','Street','Neutral','Medium','Medium',340,FALSE,'The ultimate classic New Balance.'),
('Puma Cali','Puma','Cali','PM-CALI-001','Lifestyle','Women',4800,'Leather','Casual','Street','Neutral','Medium','Medium',390,FALSE,'West coast inspired sneaker.'),
('Puma Rider FV','Puma','Rider FV','PM-RDFV-001','Lifestyle','Men',5200,'Nylon/Suede','Casual','Street','Neutral','Medium','Medium',350,FALSE,'Retro future lifestyle shoe.'),
('Skechers Uno Stand on Air','Skechers','Uno','SK-UNO-002','Lifestyle','Women',4500,'Synthetic','Casual','Street','Neutral','Medium','Medium',340,FALSE,'Air cushioned fashion sneaker.'),
('Skechers DLites','Skechers','DLites','SK-DLT-001','Lifestyle','Women',4800,'Leather/Mesh','Casual','Street','Neutral','High','Medium',380,FALSE,'The original chunky sneaker.'),
('Converse Run Star Hike','Converse','Run Star Hike','CV-RSH-001','Lifestyle','Unisex',6500,'Canvas','Casual','Street','Neutral','High','High',480,FALSE,'Platform chunky sole converse.'),
('Converse One Star','Converse','One Star','CV-OST-001','Lifestyle','Unisex',4600,'Suede','Casual','Street','Neutral','Low','Medium',400,FALSE,'Suede low top classic.'),
('Onitsuka Tiger Mexico 66','Onitsuka Tiger','Mexico 66','OT-MEX66-001','Lifestyle','Unisex',6800,'Leather','Casual','Street','Neutral','Low','Low',290,FALSE,'Sleek heritage running shoe.'),
('HOKA Clifton L','HOKA','Clifton L','HK-CLFL-001','Lifestyle','Unisex',7500,'Leather/Mesh','Casual','Street','Neutral','High','Medium',310,FALSE,'Everyday lifestyle comfort.'),
('Salomon XT-4','Salomon','XT-4','SL-XT4-001','Lifestyle','Unisex',9500,'Synthetic','Casual','Street','Stability','Medium','High',360,FALSE,'Trail style for the street.'),
('Nike Air Huarache','Nike','Air Huarache','NK-HRC-001','Lifestyle','Men',6800,'Neoprene/Leather','Casual','Street','Neutral','Medium','Medium',330,FALSE,'Foot hugging classic.'),
('Nike Mercurial Superfly 9','Nike','Mercurial Superfly 9','NK-MS9-001','Football','Men',13500,'Synthetic','Firm Ground','Grass','Neutral','Low','High',195,FALSE,'Elite speed football boot.'),
('Nike Mercurial Vapor 15','Nike','Mercurial Vapor 15','NK-MV15-001','Football','Men',12800,'Synthetic','Firm Ground','Grass','Neutral','Low','High',185,FALSE,'Low cut speed boot.'),
('Nike Phantom GX','Nike','Phantom GX','NK-PGX-001','Football','Unisex',12500,'Gripknit','Firm Ground','Grass','Neutral','Low','High',205,FALSE,'Precision and control boot.'),
('Nike Tiempo Legend 10','Nike','Tiempo Legend 10','NK-TL10-001','Football','Men',11500,'Synthetic Leather','Firm Ground','Grass','Neutral','Medium','High',230,FALSE,'Comfortable heritage boot.'),
('Adidas Predator Accuracy.1','Adidas','Predator Accuracy.1','AD-PRA1-001','Football','Men',12500,'HybridTouch','Firm Ground','Grass','Neutral','Low','High',225,FALSE,'Striking and control boot.'),
('Adidas X Crazyfast.1','Adidas','X Crazyfast.1','AD-XC1-001','Football','Men',12800,'Aeropacity','Firm Ground','Grass','Neutral','Low','High',180,FALSE,'Ultra lightweight speed boot.'),
('Adidas Copa Pure.1','Adidas','Copa Pure.1','AD-CP1-001','Football','Men',11500,'Leather','Firm Ground','Grass','Neutral','Medium','High',240,FALSE,'Premium leather touch boot.'),
('Adidas Predator Edge','Adidas','Predator Edge','AD-PRED-001','Football','Kids',4500,'Synthetic','Firm Ground','Grass','Neutral','Low','Medium',210,FALSE,'Youth control football boot.'),
('Puma Future Ultimate','Puma','Future Ultimate','PM-FUT-001','Football','Men',11000,'Fuzionfit','Firm Ground','Grass','Neutral','Low','High',215,FALSE,'Agility and playmaker boot.'),
('Puma Ultra Ultimate','Puma','Ultra Ultimate','PM-ULT-001','Football','Men',11000,'Ultraweave','Firm Ground','Grass','Neutral','Low','High',185,FALSE,'Speed focused football boot.'),
('Puma King Ultimate','Puma','King Ultimate','PM-KNG-001','Football','Men',10500,'K-Better','Firm Ground','Grass','Neutral','Medium','High',230,FALSE,'Modernized heritage boot.'),
('Mizuno Morelia Neo III','Mizuno','Morelia Neo III','MZ-MN3-001','Football','Men',14500,'K-Leather','Firm Ground','Grass','Neutral','Low','High',195,FALSE,'Made in Japan premium boot.'),
('Mizuno Alpha Japan','Mizuno','Alpha Japan','MZ-ALP-001','Football','Men',14800,'Synthetic','Firm Ground','Grass','Neutral','Low','High',190,FALSE,'Elite Japanese speed boot.'),
('New Balance Furon V7','New Balance','Furon V7','NB-FUR7-001','Football','Men',10800,'Hypoknit','Firm Ground','Grass','Neutral','Low','High',195,FALSE,'Explosive speed boot.'),
('New Balance Tekela V4','New Balance','Tekela V4','NB-TEK4-001','Football','Men',10800,'Knit','Firm Ground','Grass','Neutral','Low','High',210,FALSE,'Laceless control boot.'),
('Under Armour Magnetico','Under Armour','Clone Magnetico','UA-MAG-001','Football','Men',9500,'Clone','Firm Ground','Grass','Neutral','Medium','High',225,FALSE,'Adaptive fit football boot.'),
('Nike Premier 3','Nike','Premier 3','NK-PRM3-001','Football','Men',6500,'K-Leather','Firm Ground','Grass','Neutral','Medium','High',245,FALSE,'Classic leather football boot.'),
('Adidas Goletto VIII','Adidas','Goletto VIII','AD-GOL8-001','Football','Men',3500,'Synthetic','Firm Ground','Grass','Neutral','Low','Medium',260,FALSE,'Entry level firm ground boot.'),
('Puma Attacanto','Puma','Attacanto','PM-ATT-001','Football','Men',3200,'Synthetic','Firm Ground','Grass','Neutral','Low','Medium',255,FALSE,'Affordable durable football shoe.'),
('ASICS DS Light','ASICS','DS Light','AS-DSL-001','Football','Men',7500,'K-Leather','Firm Ground','Grass','Neutral','Medium','High',220,FALSE,'Comfortable leather boot.'),
('Nike LeBron 21','Nike','LeBron 21','NK-LBJ21-001','Basketball','Men',11000,'Mesh/Leather','Game','Court','Stability','Maximum','High',400,FALSE,'King James flagship shoe.'),
('Nike KD 16','Nike','KD 16','NK-KD16-001','Basketball','Men',9500,'Mesh','Game','Court','Neutral','High','High',380,FALSE,'Kevin Durant versatile shoe.'),
('Nike Zoom Freak 5','Nike','Zoom Freak 5','NK-ZF5-001','Basketball','Men',7800,'Mesh','Game','Court','Neutral','Medium','High',360,FALSE,'Giannis signature basketball shoe.'),
('Nike Ja 1','Nike','Ja 1','NK-JA1-001','Basketball','Men',6800,'Mesh','Game','Court','Neutral','Medium','High',340,FALSE,'Lightweight bouncy signature shoe.'),
('Nike Tatum 1','Nike','Tatum 1','NK-TAT1-001','Basketball','Men',7200,'Mesh','Game','Court','Neutral','Medium','High',330,FALSE,'Ultra light basketball shoe.'),
('Nike Luka 2','Nike','Luka 2','NK-LUK2-001','Basketball','Men',7500,'Synthetic/Mesh','Game','Court','Stability','Medium','High',390,FALSE,'Step-back focused control shoe.'),
('Adidas Trae Young 3','Adidas','Trae Young 3','AD-TY3-001','Basketball','Men',8200,'Knit','Game','Court','Neutral','Medium','High',370,FALSE,'Agility and speed basketball shoe.'),
('Adidas AE 1','Adidas','AE 1','AD-AE1-001','Basketball','Men',7500,'Synthetic','Game','Court','Stability','High','High',410,FALSE,'Anthony Edwards signature shoe.'),
('Adidas Harden Vol 7','Adidas','Harden Vol 7','AD-HRD7-001','Basketball','Men',9200,'Textile','Game','Court','Stability','High','High',420,FALSE,'James Harden signature shoe.'),
('Adidas DON Issue 5','Adidas','DON Issue 5','AD-DON5-001','Basketball','Men',6800,'Mesh','Game','Court','Neutral','Medium','High',380,FALSE,'Donovan Mitchell signature shoe.'),
('Under Armour Curry 11','Under Armour','Curry 11','UA-CUR11-001','Basketball','Men',9500,'Knit','Game','Court','Neutral','Medium','High',350,FALSE,'Stephen Curry signature shoe.'),
('Under Armour Spawn 5','Under Armour','Spawn 5','UA-SPW5-001','Basketball','Men',6200,'Mesh','Game','Court','Neutral','Medium','High',360,FALSE,'Anatomical design basketball shoe.'),
('Puma MB.03','Puma','MB.03','PM-MB03-001','Basketball','Men',8500,'Mesh','Game','Court','Neutral','Medium','High',390,FALSE,'LaMelo Ball signature shoe.'),
('Puma All-Pro Nitro','Puma','All-Pro Nitro','PM-APN-001','Basketball','Men',7500,'Mesh','Game','Court','Neutral','High','High',380,FALSE,'Responsive nitro foam basketball shoe.'),
('Puma Scoot Zeros','Puma','Scoot Zeros','PM-SCZ-001','Basketball','Men',6500,'Mesh','Game','Court','Neutral','Medium','High',370,FALSE,'Scoot Henderson signature shoe.'),
('New Balance Two WXY V4','New Balance','Two WXY V4','NB-TW4-001','Basketball','Men',7800,'Mesh','Game','Court','Neutral','High','High',380,FALSE,'Positionless basketball shoe.'),
('New Balance Kawhi III','New Balance','Kawhi III','NB-KAW3-001','Basketball','Men',9200,'Synthetic','Game','Court','Stability','Medium','High',400,FALSE,'Kawhi Leonard signature shoe.'),
('ASICS Nova Surge 2','ASICS','Nova Surge 2','AS-NVS2-001','Basketball','Men',8500,'Mesh','Game','Court','Stability','High','High',410,FALSE,'Maximum cushioning hoops shoe.'),
('Reebok Shaq Attaq','Reebok','Shaq Attaq','RB-SHQ-001','Basketball','Men',9500,'Leather','Retro','Court','Stability','Medium','Medium',460,FALSE,'Shaquille ONeal retro shoe.'),
('Converse All Star BB','Converse','BB Trilliant','CV-BBT-001','Basketball','Men',7200,'Mesh','Game','Court','Neutral','Medium','High',360,FALSE,'Responsive modern converse hoops shoe.'),
('Nike Zoom Vapor Pro 2','Nike','Vapor Pro 2','NK-ZVP2-001','Tennis','Men',7200,'Mesh','Match','Court','Neutral','Medium','High',360,FALSE,'Lightweight speed tennis shoe.'),
('Nike Zoom Vapor Cage 4','Nike','Vapor Cage 4','NK-ZVC4-001','Tennis','Men',8500,'Synthetic','Match','Court','Stability','High','High',410,FALSE,'Durable hard court tennis shoe.'),
('Adidas Barricade','Adidas','Barricade','AD-BAR-001','Tennis','Men',8200,'Mesh','Match','Court','Stability','High','High',400,FALSE,'Ultimate stability tennis shoe.'),
('Adidas Ubersonic 4','Adidas','Ubersonic 4','AD-UBS4-001','Tennis','Women',7500,'Primeknit','Match','Court','Neutral','Medium','High',340,FALSE,'Lightweight responsive tennis shoe.'),
('ASICS Gel-Resolution 9','ASICS','Gel-Resolution 9','AS-RES9-001','Tennis','Men',8500,'PU/Mesh','Match','Court','Stability','High','High',400,FALSE,'Premium baseline stability shoe.'),
('ASICS Court FF 3','ASICS','Court FF 3','AS-CFF3-002','Tennis','Men',9500,'PU/Mesh','Match','Court','Stability','High','High',415,FALSE,'Novak Djokovic signature shoe.'),
('New Balance CT302','New Balance','CT302','NB-CT302-001','Tennis','Women',5800,'Leather','Casual','Court','Neutral','Medium','Medium',420,FALSE,'Platform lifestyle tennis shoe.'),
('New Balance Coco CG1','New Balance','Coco CG1','NB-CG1-001','Tennis','Women',9200,'Synthetic','Match','Court','Stability','Medium','High',390,FALSE,'Coco Gauff signature shoe.'),
('K-Swiss Hypercourt 2','K-Swiss','Hypercourt Express 2','KS-HYP2-001','Tennis','Men',6500,'Mesh/PU','Match','Court','Neutral','Medium','High',380,FALSE,'Comfortable wide fit tennis shoe.'),
('Wilson Rush Pro 4.0','Wilson','Rush Pro 4.0','WL-RP4-001','Tennis','Men',7800,'Mesh','Match','Court','Stability','High','High',395,FALSE,'Dynamic court movement shoe.'),
('Nike SB Dunk Low','Nike','SB Dunk Low','NK-SBDL-001','Skateboarding','Unisex',7500,'Leather/Suede','Skate','Street','Neutral','Medium','High',410,FALSE,'Iconic padded skate shoe.'),
('Nike SB Nyjah 3','Nike','Nyjah 3','NK-NYJ3-001','Skateboarding','Men',6200,'Rubber/Mesh','Skate','Street','Neutral','Medium','High',360,FALSE,'Technical durable skate shoe.'),
('Nike SB Ishod','Nike','Ishod','NK-ISH-001','Skateboarding','Men',6500,'Suede','Skate','Street','Neutral','Low','High',380,FALSE,'Ishod Wair signature shoe.'),
('Adidas Busenitz','Adidas','Busenitz','AD-BSN-001','Skateboarding','Men',5500,'Suede','Skate','Street','Neutral','Low','High',390,FALSE,'Football inspired skate shoe.'),
('Adidas Tyshawn','Adidas','Tyshawn','AD-TYS-001','Skateboarding','Men',5800,'Leather','Skate','Street','Stability','Medium','High',420,FALSE,'Mid top skate shoe.'),
('Vans Half Cab','Vans','Half Cab','VN-HC-001','Skateboarding','Unisex',5200,'Suede','Skate','Street','Stability','Medium','High',410,FALSE,'Steve Caballero signature shoe.'),
('Vans Kyle Walker','Vans','Kyle Walker','VN-KW-001','Skateboarding','Men',5500,'Suede','Skate','Street','Neutral','Medium','High',400,FALSE,'Wafflecup skate shoe.'),
('Vans Authentic','Vans','Authentic','VN-AUTH-001','Skateboarding','Unisex',3500,'Canvas','Casual Skate','Street','Neutral','Low','Medium',340,FALSE,'The original Vans silhouette.'),
('Converse One Star Pro','Converse','One Star Pro','CV-OSP-001','Skateboarding','Unisex',4800,'Suede','Skate','Street','Neutral','Low','High',390,FALSE,'Skate upgraded classic.'),
('New Balance Numeric 272','New Balance','Numeric 272','NB-NM272-001','Skateboarding','Men',4900,'Suede/Canvas','Skate','Street','Neutral','Low','High',380,FALSE,'Vulcanized board feel shoe.'),
('Nike Pegasus Trail 4','Nike','Pegasus Trail 4','NK-PT4-001','Trail Running','Men',7500,'Mesh','Trail Running','Trail','Neutral','Medium','Medium',290,FALSE,'Road to trail hybrid shoe.'),
('Nike Wildhorse 8','Nike','Wildhorse 8','NK-WH8-001','Trail Running','Women',7200,'Mesh','Trail Running','Trail','Neutral','Medium','High',300,FALSE,'Rugged trail running shoe.'),
('Adidas Terrex Speed Ultra','Adidas','Speed Ultra','AD-TSU-001','Trail Running','Men',9500,'Mesh','Trail Racing','Trail','Neutral','Medium','High',245,FALSE,'Fast lightweight trail racer.'),
('ASICS Trabuco Max 2','ASICS','Trabuco Max 2','AS-TRB2-001','Trail Running','Men',7800,'Mesh','Trail Running','Trail','Neutral','Maximum','High',305,FALSE,'Max cushion trail runner.'),
('HOKA Speedgoat 5','HOKA','Speedgoat 5','HK-SG5-001','Trail Running','Unisex',8500,'Jacquard Mesh','Trail Running','Trail','Neutral','High','High',291,FALSE,'Grippy technical trail shoe.'),
('HOKA Mafate Speed 4','HOKA','Mafate Speed 4','HK-MS4-001','Trail Running','Men',9200,'Mesh','Trail Running','Trail','Neutral','High','High',295,FALSE,'Responsive technical trail shoe.'),
('Salomon Speedcross 6','Salomon','Speedcross 6','SL-SC6-001','Trail Running','Men',8800,'Ripstop','Trail Running','Mud','Neutral','Medium','Maximum',298,FALSE,'Aggressive grip for mud.'),
('Salomon Sense Ride 5','Salomon','Sense Ride 5','SL-SR5-001','Trail Running','Women',7500,'Mesh','Trail Running','Trail','Neutral','Medium','Medium',286,FALSE,'Versatile all around trail shoe.'),
('Brooks Cascadia 17','Brooks','Cascadia 17','BK-CAS17-001','Trail Running','Men',7800,'Mesh','Trail Running','Trail','Stability','Medium','High',311,FALSE,'Stable protective trail shoe.'),
('New Balance Hierro V7','New Balance','Hierro V7','NB-HRO7-001','Trail Running','Men',7500,'Mesh','Trail Running','Trail','Neutral','High','High',300,FALSE,'Cushioned vibram trail shoe.'),
('Salomon X Ultra 4 GTX','Salomon','X Ultra 4 GTX','SL-XU4-001','Hiking','Men',9500,'Synthetic','Hiking','Trail','Stability','Medium','High',390,TRUE,'Agile waterproof hiker.'),
('Salomon Quest 4 GTX','Salomon','Quest 4 GTX','SL-QST4-001','Hiking','Men',12500,'Nubuck','Backpacking','Trail','Maximum','High','Maximum',655,TRUE,'Heavy duty backpacking boot.'),
('Merrell Moab 3 GTX','Merrell','Moab 3 GTX','MR-MO3-001','Hiking','Men',7800,'Leather/Mesh','Hiking','Trail','Stability','Medium','High',460,TRUE,'Mother of all boots.'),
('Merrell Rogue Hiker','Merrell','Rogue Hiker','MR-RGH-001','Hiking','Men',11000,'Ballistic Mesh','Backpacking','Trail','Stability','High','Maximum',530,TRUE,'Lightweight backpacking boot.'),
('Columbia Newton Ridge','Columbia','Newton Ridge Plus','CL-NWT-001','Hiking','Women',6500,'Leather/Mesh','Hiking','Trail','Stability','Medium','High',410,TRUE,'Classic waterproof hiking boot.'),
('Columbia Facet 75','Columbia','Facet 75 Alpha','CL-FCT-001','Hiking','Men',7200,'Mesh','Fast Hiking','Trail','Neutral','High','High',400,TRUE,'Modern sneaker like hiker.'),
('Adidas Terrex Free Hiker 2','Adidas','Free Hiker 2','AD-TFH2-001','Hiking','Men',11500,'Primeknit','Hiking','Trail','Neutral','Maximum','High',445,TRUE,'Boost cushioned hiking boot.'),
('HOKA Kaha 2 GTX','HOKA','Kaha 2 GTX','HK-KAH2-001','Hiking','Women',11800,'Nubuck','Backpacking','Trail','Stability','Maximum','High',476,TRUE,'Plush waterproof hiking boot.'),
('Timberland Mt Maddsen','Timberland','Mt Maddsen','TB-MTM-001','Hiking','Men',7500,'Leather','Hiking','Trail','Stability','Medium','High',500,TRUE,'Classic leather hiking boot.'),
('Keen Targhee III','Keen','Targhee III','KN-TRG3-001','Hiking','Men',8200,'Leather','Hiking','Trail','Stability','Medium','High',490,TRUE,'Roomy toe box hiker.'),
('Nike Air Force 1 Kids','Nike','Air Force 1','NK-AF1K-001','Kids','Boys',3500,'Leather','Casual','Street','Neutral','Medium','Medium',310,FALSE,'Classic AF1 for kids.'),
('Adidas Grand Court Kids','Adidas','Grand Court','AD-GCK-001','Kids','Unisex',2800,'Synthetic','Casual','Street','Neutral','Low','Medium',250,FALSE,'Tennis style kids shoe.'),
('Puma Smash v2 Kids','Puma','Smash v2','PM-SMK-001','Kids','Girls',2500,'Synthetic','Casual','Street','Neutral','Low','Medium',220,FALSE,'Everyday kids sneaker.'),
('Skechers Twinkle Toes','Skechers','Twinkle Toes','SK-TWN-001','Kids','Girls',3200,'Canvas','Casual','Street','Neutral','Low','Medium',240,FALSE,'Light up casual shoe.'),
('Vans Old Skool Kids','Vans','Old Skool','VN-OSK-001','Kids','Unisex',2900,'Canvas','Casual','Street','Neutral','Low','Medium',260,FALSE,'Classic skate shoe for kids.'),
('New Balance 574 Kids','New Balance','574','NB-574K-001','Kids','Boys',3200,'Suede/Mesh','Casual','Street','Neutral','Medium','Medium',240,FALSE,'Classic NB style for kids.'),
('ASICS Contend 8 Kids','ASICS','Contend 8','AS-CON8-001','Kids','Unisex',2800,'Mesh','Running','Road','Neutral','Medium','Medium',210,FALSE,'Durable kids running shoe.'),
('Under Armour Assert 10 Kids','Under Armour','Assert 10','UA-AST10-001','Kids','Boys',2900,'Mesh','Running','Road','Neutral','Medium','Medium',220,FALSE,'Breathable active kids shoe.'),
('Nike Dynamo Go Kids','Nike','Dynamo Go','NK-DYN-001','Kids','Unisex',3400,'Foam/Textile','Casual','Street','Neutral','Medium','Low',180,FALSE,'Easy slip on kids shoe.'),
('Adidas Duramo Kids','Adidas','Duramo','AD-DURK-001','Kids','Girls',2700,'Mesh','Running','Road','Neutral','Medium','Medium',200,FALSE,'Lightweight kids active shoe.'),
('Crocs Classic Clog','Crocs','Classic Clog','CR-CLA-001','Sandals','Unisex',2500,'Croslite','Casual','Mixed','Neutral','Medium','Low',170,TRUE,'The iconic comfortable clog.'),
('Birkenstock Arizona','Birkenstock','Arizona','BK-ARZ-001','Sandals','Unisex',5500,'Birko-Flor','Casual','Street','Arch Support','Firm','Medium',250,FALSE,'Classic cork footbed sandal.'),
('Nike Victori One','Nike','Victori One','NK-VIC-001','Sandals','Men',1800,'Synthetic','Recovery','Street','Neutral','Soft','Low',150,TRUE,'Comfortable shower slide.'),
('Adidas Adilette Comfort','Adidas','Adilette Comfort','AD-ADI-001','Sandals','Women',2000,'Synthetic','Recovery','Street','Neutral','Soft','Low',160,TRUE,'Plush footbed slide.'),
('Teva Hurricane XLT2','Teva','Hurricane XLT2','TV-HUR-001','Sandals','Unisex',3800,'Webbing','Outdoor','Trail','Neutral','Medium','High',290,TRUE,'Rugged outdoor sport sandal.'),
('Timberland 6-Inch Premium','Timberland','6-Inch Premium','TB-6IN-001','Boots','Men',11000,'Nubuck','Lifestyle','Mixed','Stability','Medium','High',800,TRUE,'The original yellow boot.'),
('Dr Martens 1460','Dr. Martens','1460','DM-1460-001','Boots','Unisex',9500,'Leather','Lifestyle','Street','Neutral','Firm','Medium',750,FALSE,'Classic 8-eye combat boot.'),
('Caterpillar Colorado','Caterpillar','Colorado','CAT-COL-001','Boots','Men',7800,'Leather','Lifestyle','Mixed','Stability','Firm','High',850,FALSE,'Rugged workwear lifestyle boot.'),
('Blundstone 585','Blundstone','585 Classic','BL-585-001','Boots','Unisex',10500,'Leather','Lifestyle','Mixed','Neutral','Medium','Medium',500,TRUE,'Chelsea boot with rustic finish.'),
('UGG Classic Short','UGG','Classic Short','UG-CLS-001','Boots','Women',8500,'Sheepskin','Casual','Street','Neutral','Soft','Low',350,FALSE,'Warm sheepskin winter boot.');