INSERT INTO Products (ProductName, ProductBrand, ProductModel, ProductSKU, ProductCategory, ProductGender, ProductPrice, 
ProductMaterial, ProductUsage, ProductSurface, ProductSupportType, 
ProductCushioning, ProductBreathability, ProductWeight, ProductWaterproof, ProductDescription) VALUES
('Nike Pegasus 40','Nike','Pegasus 40','NK-PEG40-001','Running','Men',5500.00,'Mesh','Daily Running','Road','Neutral','Medium','High',288.00,FALSE,'Everyday neutral running shoe.'),
('Nike Pegasus 40 Women','Nike','Pegasus 40','NK-PEG40-002','Running','Women',5500.00,'Mesh','Daily Running','Road','Neutral','Medium','High',242.00,FALSE,'Everyday neutral running shoe.'),
('Nike ZoomX Vaporfly 3','Nike','Vaporfly 3','NK-VPF3-001','Running','Unisex',12500.00,'Flyknit','Racing','Road','Neutral','High','High',198.00,FALSE,'Elite marathon racing shoe.'),
('Nike InfinityRN 4','Nike','InfinityRN 4','NK-INF4-001','Running','Men',7900.00,'Flyknit','Daily Running','Road','Stability','High','High',315.00,FALSE,'Supportive reactx foam runner.'),
('Nike Structure 25','Nike','Structure 25','NK-STR25-001','Running','Women',6200.00,'Mesh','Daily Running','Road','Stability','Medium','High',265.00,FALSE,'Classic stability running shoe.'),
('Nike Invincible 3','Nike','Invincible 3','NK-INV3-001','Running','Men',9200.00,'Flyknit','Long Distance','Road','Neutral','Maximum','High',310.00,FALSE,'Maximum cushioning for long runs.'),
('Nike Vomero 17','Nike','Vomero 17','NK-VOM17-001','Running','Men',8200.00,'Mesh','Daily Running','Road','Neutral','High','High',300.00,FALSE,'Premium daily trainer with ZoomX.'),
('Nike Winflo 10','Nike','Winflo 10','NK-WIN10-001','Running','Women',4500.00,'Mesh','Daily Running','Road','Neutral','Medium','High',260.00,FALSE,'Affordable daily runner.'),
('Nike Downshifter 13','Nike','Downshifter 13','NK-DS13-001','Running','Men',3500.00,'Mesh','Daily Running','Road','Neutral','Low','High',270.00,FALSE,'Entry-level running shoe.'),
('Nike Revolution 7','Nike','Revolution 7','NK-REV7-001','Running','Women',3200.00,'Mesh','Daily Running','Road','Neutral','Low','High',250.00,FALSE,'Budget-friendly daily shoe.'),
('Adidas Ultraboost Light','Adidas','Ultraboost Light','AD-UBL-001','Running','Men',7500.00,'Primeknit','Daily Running','Road','Neutral','High','High',299.00,FALSE,'Premium cushioned running shoe.'),
('Adidas Adizero Adios Pro 3','Adidas','Adios Pro 3','AD-AAP3-001','Running','Unisex',11500.00,'Mesh','Racing','Road','Neutral','High','High',215.00,FALSE,'Carbon-plated racing shoe.'),
('Adidas Boston 12','Adidas','Boston 12','AD-BST12-001','Running','Men',7400.00,'Mesh','Speed Training','Road','Neutral','Medium','High',255.00,FALSE,'Up-tempo training shoe.'),
('Adidas Supernova Rise','Adidas','Supernova Rise','AD-SNR-001','Running','Women',6500.00,'Mesh','Daily Running','Road','Neutral','Medium','High',243.00,FALSE,'Comfortable daily distance shoe.'),
('Adidas Duramo SL','Adidas','Duramo SL','AD-DSL-001','Running','Men',3200.00,'Mesh','Daily Running','Road','Neutral','Medium','High',280.00,FALSE,'Everyday affordable runner.'),
('Adidas Solarboost 5','Adidas','Solarboost 5','AD-SLB5-001','Running','Women',6800.00,'Mesh','Daily Running','Road','Neutral','High','High',279.00,FALSE,'Reliable daily trainer.'),
('Adidas Adizero SL','Adidas','Adizero SL','AD-ADSL-001','Running','Men',5500.00,'Mesh','Speed Training','Road','Neutral','Medium','High',240.00,FALSE,'Lightweight daily trainer.'),
('ASICS Gel-Nimbus 26','ASICS','Gel-Nimbus 26','AS-NIM26-001','Running','Women',8200.00,'Mesh','Daily Running','Road','Neutral','Maximum','High',290.00,FALSE,'Max cushion long distance shoe.'),
('ASICS Novablast 4','ASICS','Novablast 4','AS-NOV4-001','Running','Men',6800.00,'Mesh','Daily Running','Road','Neutral','High','High',260.00,FALSE,'Bouncy daily trainer.'),
('ASICS Gel-Cumulus 26','ASICS','Gel-Cumulus 26','AS-CUM26-001','Running','Men',6800.00,'Mesh','Daily Running','Road','Neutral','Medium','High',255.00,FALSE,'Soft everyday running shoe.'),
('ASICS Gel-Kayano 30','ASICS','Gel-Kayano 30','AS-KAY30-001','Running','Women',8500.00,'Knit','Daily Running','Road','Stability','High','High',263.00,FALSE,'Premium stability running shoe.'),
('ASICS GT-2000 12','ASICS','GT-2000 12','AS-GT12-001','Running','Men',6500.00,'Mesh','Daily Running','Road','Stability','Medium','High',270.00,FALSE,'Go-to stability trainer.'),
('ASICS Magic Speed 3','ASICS','Magic Speed 3','AS-MGS3-001','Running','Unisex',7500.00,'Mesh','Racing','Road','Neutral','Medium','High',220.00,FALSE,'Carbon-plated speed shoe.'),
('ASICS Superblast','ASICS','Superblast','AS-SPB-001','Running','Unisex',9500.00,'Mesh','Long Distance','Road','Neutral','Maximum','High',239.00,FALSE,'Ultra-cushioned lightweight trainer.'),
('Brooks Ghost 15','Brooks','Ghost 15','BK-GHO15-001','Running','Women',6500.00,'Mesh','Daily Running','Road','Neutral','Medium','High',258.00,FALSE,'Reliable daily running shoe.'),
('Brooks Glycerin 21','Brooks','Glycerin 21','BK-GLY21-001','Running','Men',7800.00,'Mesh','Daily Running','Road','Neutral','Maximum','High',289.00,FALSE,'Ultra-soft cushioning running shoe.'),
('Brooks Adrenaline GTS 23','Brooks','Adrenaline GTS 23','BK-ADR23-001','Running','Men',7200.00,'Mesh','Daily Running','Road','Stability','Medium','High',286.00,FALSE,'Go-to stability shoe.'),
('Brooks Hyperion Tempo','Brooks','Hyperion Tempo','BK-HYP-001','Running','Women',6800.00,'Woven','Speed Training','Road','Neutral','Low','High',190.00,FALSE,'Lightweight speed workout shoe.'),
('Brooks Launch 10','Brooks','Launch 10','BK-LNC10-001','Running','Men',5500.00,'Mesh','Daily Running','Road','Neutral','Medium','High',235.00,FALSE,'Lightweight daily trainer.'),
('Brooks Revel 6','Brooks','Revel 6','BK-RVL6-001','Running','Women',5200.00,'Knit','Daily Running','Road','Neutral','Medium','Medium',240.00,FALSE,'Versatile runner for gym and road.'),
('New Balance 1080v13','New Balance','1080v13','NB-1080V13-001','Running','Men',8500.00,'Knit','Daily Running','Road','Neutral','Maximum','High',262.00,FALSE,'Premium cushioned daily runner.'),
('New Balance SuperComp Elite v4','New Balance','SC Elite v4','NB-SCE4-001','Running','Unisex',12000.00,'Mesh','Racing','Road','Neutral','High','High',235.00,FALSE,'Race day carbon shoe.'),
('New Balance 880v14','New Balance','880v14','NB-880V14-001','Running','Men',6800.00,'Mesh','Daily Running','Road','Neutral','Medium','High',269.00,FALSE,'Workhorse daily running shoe.'),
('New Balance Rebel v4','New Balance','Rebel v4','NB-REB4-001','Running','Women',6900.00,'Mesh','Speed Training','Road','Neutral','Medium','High',196.00,FALSE,'Fast and responsive trainer.'),
('New Balance Vongo v6','New Balance','Vongo v6','NB-VON6-001','Running','Men',7500.00,'Mesh','Daily Running','Road','Stability','High','High',285.00,FALSE,'Stable and cushioned daily runner.'),
('HOKA Clifton 9','HOKA','Clifton 9','HK-CLF9-001','Running','Women',7200.00,'Mesh','Daily Running','Road','Neutral','High','High',248.00,FALSE,'Lightweight max cushion shoe.'),
('HOKA Bondi 8','HOKA','Bondi 8','HK-BND8-001','Running','Men',7800.00,'Mesh','Recovery','Road','Neutral','Maximum','High',307.00,FALSE,'Maximum comfort and protection.'),
('HOKA Mach 6','HOKA','Mach 6','HK-MCH6-001','Running','Men',7500.00,'Mesh','Speed Training','Road','Neutral','Medium','High',232.00,FALSE,'Snappy everyday speed shoe.'),
('HOKA Arahi 7','HOKA','Arahi 7','HK-ARH7-001','Running','Women',7200.00,'Mesh','Daily Running','Road','Stability','Medium','High',228.00,FALSE,'Dynamic stability running shoe.'),
('HOKA Rincon 3','HOKA','Rincon 3','HK-RNC3-001','Running','Men',6200.00,'Mesh','Speed Training','Road','Neutral','Medium','High',210.00,FALSE,'Lightweight fast trainer.'),
('Puma Magnify Nitro 2','Puma','Magnify Nitro 2','PM-MGN2-001','Running','Men',6800.00,'Mesh','Daily Running','Road','Neutral','Maximum','High',274.00,FALSE,'Thick nitro foam cushioning.'),
('Puma Velocity Nitro 3','Puma','Velocity Nitro 3','PM-VLN3-001','Running','Women',5900.00,'Mesh','Daily Running','Road','Neutral','Medium','High',245.00,FALSE,'Versatile everyday trainer.'),
('Puma Deviate Nitro 2','Puma','Deviate Nitro 2','PM-DEV2-001','Running','Men',7900.00,'Mesh','Speed Training','Road','Neutral','High','High',260.00,FALSE,'Plated training running shoe.'),
('Puma ForeverRun Nitro','Puma','ForeverRun Nitro','PM-FRN-001','Running','Women',7500.00,'Mesh','Daily Running','Road','Stability','High','High',224.00,FALSE,'Stability with nitro foam.'),
('Mizuno Wave Rider 27','Mizuno','Wave Rider 27','MZ-WVR27-001','Running','Men',6500.00,'Mesh','Daily Running','Road','Neutral','Medium','High',280.00,FALSE,'Smooth transition running shoe.'),
('Mizuno Wave Inspire 19','Mizuno','Wave Inspire 19','MZ-WVI19-001','Running','Women',6500.00,'Mesh','Daily Running','Road','Stability','Medium','High',245.00,FALSE,'Supportive stability runner.'),
('Mizuno Wave Sky 7','Mizuno','Wave Sky 7','MZ-WVS7-001','Running','Men',7800.00,'Knit','Daily Running','Road','Neutral','Maximum','High',300.00,FALSE,'Floating feel maximum cushion.'),
('Skechers GO RUN Ride 11','Skechers','Ride 11','SK-GR11-001','Running','Men',5200.00,'Mesh','Daily Running','Road','Neutral','High','High',238.00,FALSE,'Hyper burst cushioned runner.'),
('Skechers Max Road 6','Skechers','Max Road 6','SK-MXR6-001','Running','Unisex',5800.00,'Mesh','Long Distance','Road','Neutral','Maximum','High',285.00,FALSE,'Long distance max cushion.'),
('Under Armour Velociti Wind 2','Under Armour','Velociti Wind 2','UA-FVW2-001','Running','Men',6200.00,'Knit','Speed Training','Road','Neutral','Low','High',236.00,FALSE,'Rubberless fast running shoe.'),
('Under Armour HOVR Machina 3','Under Armour','Machina 3','UA-HVM3-001','Running','Women',6400.00,'Mesh','Daily Running','Road','Neutral','Medium','High',269.00,FALSE,'Smart connected running shoe.'),
('Nike Motiva','Nike','Motiva','NK-MTV-001','Walking','Women',4500.00,'Mesh','Walking','Road','Neutral','High','Medium',260.00,FALSE,'Smooth walking experience.'),
('Adidas Walk Cloud','Adidas','Walk Cloud','AD-WKC-001','Walking','Men',3900.00,'Mesh','Walking','Road','Neutral','Medium','High',280.00,FALSE,'Cloud-like walking comfort.'),
('ASICS Gel-Mission','ASICS','Gel-Mission','AS-MIS-001','Walking','Men',3600.00,'Synthetic','Walking','Road','Neutral','Medium','Medium',320.00,FALSE,'Durable walking shoe.'),
('New Balance 577','New Balance','577','NB-577-001','Walking','Women',4200.00,'Leather','Walking','Road','Stability','Medium','Medium',310.00,FALSE,'All day walking support.'),
('Skechers GO WALK 6','Skechers','GO WALK 6','SK-GW6-001','Walking','Men',4100.00,'Mesh','Walking','Road','Neutral','Medium','High',245.00,FALSE,'Slip-on walking comfort.'),
('Skechers GO WALK 7','Skechers','GO WALK 7','SK-GW7-001','Walking','Women',4300.00,'Mesh','Walking','Road','Neutral','Medium','High',240.00,FALSE,'Latest slip-on walking comfort.'),
('Skechers Arch Fit Walk','Skechers','Arch Fit Walk','SK-AFW-001','Walking','Women',4800.00,'Mesh','Walking','Road','Arch Support','High','High',260.00,FALSE,'Podiatrist certified arch support.'),
('Brooks Addiction Walker 2','Brooks','Addiction Walker 2','BK-AW2-001','Walking','Men',6500.00,'Leather','Walking','Road','Motion Control','High','Low',380.00,FALSE,'Maximum support leather walker.'),
('HOKA Transport','HOKA','Transport','HK-TRP-001','Walking','Unisex',8500.00,'Cordura','Commuting','Road','Neutral','High','Medium',318.00,FALSE,'Comfortable urban commuter.'),
('HOKA Transport GTX','HOKA','Transport GTX','HK-TRPG-001','Walking','Unisex',9500.00,'Mesh','Commuting','Mixed','Neutral','High','Medium',330.00,TRUE,'Waterproof daily commuter shoe.'),
('Puma Walk Lite','Puma','Walk Lite','PM-WKL-001','Walking','Women',3200.00,'Mesh','Walking','Road','Neutral','Low','High',210.00,FALSE,'Ultra lightweight walking shoe.'),
('Under Armour Essential','Under Armour','Essential','UA-ESW-001','Walking','Men',3800.00,'Mesh','Walking','Road','Neutral','Medium','High',255.00,FALSE,'Breathable all day walking.'),
('Reebok Walk Ultra 7 DMX','Reebok','Walk Ultra 7','RB-WU7-001','Walking','Men',4200.00,'Leather','Walking','Road','Neutral','High','Low',350.00,FALSE,'Cushioned leather walking shoe.'),
('New Balance 877','New Balance','877','NB-877-001','Walking','Men',4500.00,'Suede/Mesh','Walking','Road','Stability','Medium','High',325.00,FALSE,'Classic heritage walker.'),
('Clarks Wave 2.0','Clarks','Wave 2.0','CL-WV2-001','Walking','Women',5200.00,'Leather','Walking','Road','Neutral','Medium','Low',310.00,TRUE,'Waterproof curved sole walker.'),
('Nike Metcon 9','Nike','Metcon 9','NK-MTC9-002','Training','Men',7200.00,'Mesh','Gym','Indoor','Stability','Low','High',360.00,FALSE,'Ultimate cross training shoe.'),
('Nike Metcon 9 Women','Nike','Metcon 9','NK-MTC9-003','Training','Women',7200.00,'Mesh','Gym','Indoor','Stability','Low','High',310.00,FALSE,'Ultimate cross training shoe for women.'),
('Nike SuperRep Go 3','Nike','SuperRep Go 3','NK-SRG3-001','Training','Women',4900.00,'Flyknit','HIIT','Indoor','Neutral','Medium','High',240.00,FALSE,'Lightweight HIIT workout shoe.'),
('Nike Free Metcon 5','Nike','Free Metcon 5','NK-FM5-001','Training','Men',6500.00,'Mesh','Gym','Indoor','Neutral','Medium','High',290.00,FALSE,'Flexible front, stable heel.'),
('Adidas Dropset 2','Adidas','Dropset 2','AD-DRP2-001','Training','Men',6800.00,'Mesh','Weightlifting','Indoor','Stability','Low','High',370.00,FALSE,'Stable base for heavy lifts.'),
('Adidas Powerlift 5','Adidas','Powerlift 5','AD-PWL5-001','Training','Unisex',5800.00,'Canvas','Weightlifting','Indoor','Stability','Low','Medium',400.00,FALSE,'Dedicated weightlifting shoe.'),
('Adidas Rapidmove','Adidas','Rapidmove','AD-RPM-001','Training','Women',4500.00,'Mesh','HIIT','Indoor','Neutral','Medium','High',250.00,FALSE,'Agile indoor workout shoe.'),
('Reebok Nano X3','Reebok','Nano X3','RB-NNX3-001','Training','Unisex',6900.00,'Flexweave','Gym','Indoor','Stability','Medium','High',340.00,FALSE,'Versatile crossfit trainer.'),
('Reebok Nano X4','Reebok','Nano X4','RB-NNX4-001','Training','Men',7500.00,'Flexweave','Gym','Indoor','Stability','Medium','High',330.00,FALSE,'Upgraded crossfit trainer.'),
('Reebok Legacy Lifter III','Reebok','Legacy Lifter III','RB-LL3-001','Training','Men',9500.00,'Leather','Weightlifting','Indoor','Stability','Low','Low',450.00,FALSE,'Olympic weightlifting shoe.'),
('Under Armour TriBase Reign 5','Under Armour','TriBase Reign 5','UA-TBR5-001','Training','Men',6500.00,'Mesh','Gym','Indoor','Stability','Low','High',330.00,FALSE,'Low to ground gym shoe.'),
('Under Armour Project Rock 6','Under Armour','Project Rock 6','UA-PR6-001','Training','Unisex',8200.00,'Knit','Gym','Indoor','Stability','Medium','High',350.00,FALSE,'Dwayne Johnson signature trainer.'),
('Puma PWRFrame TR 2','Puma','PWRFrame TR 2','PM-PWT2-001','Training','Women',4600.00,'Mesh','HIIT','Indoor','Neutral','Medium','High',270.00,FALSE,'Supportive cardio trainer.'),
('Puma Fuse 2.0','Puma','Fuse 2.0','PM-FUS2-001','Training','Men',5500.00,'Mesh','Gym','Indoor','Stability','Low','High',340.00,FALSE,'Strength training shoe.'),
('NOBULL Outwork','NOBULL','Outwork','NB-OUT-001','Training','Unisex',8500.00,'SuperFabric','Gym','Indoor','Stability','Low','Medium',310.00,FALSE,'Indestructible cross training shoe.'),
('Nike Air Force 1 07','Nike','Air Force 1','NK-AF107-001','Lifestyle','Unisex',6200.00,'Leather','Casual','Street','Neutral','Medium','Low',430.00,FALSE,'Classic white sneaker.'),
('Nike Dunk Low','Nike','Dunk Low','NK-DNKL-001','Lifestyle','Unisex',6500.00,'Leather','Casual','Street','Neutral','Low','Low',410.00,FALSE,'Iconic retro hoops shoe.'),
('Nike Air Max 90','Nike','Air Max 90','NK-AM90-001','Lifestyle','Men',7200.00,'Leather/Mesh','Casual','Street','Neutral','Medium','Medium',390.00,FALSE,'Classic visible air cushioning.'),
('Nike Air Max 270','Nike','Air Max 270','NK-AM270-001','Lifestyle','Women',7800.00,'Mesh','Casual','Street','Neutral','High','High',320.00,FALSE,'Large air heel unit.'),
('Nike Blazer Mid 77','Nike','Blazer Mid 77','NK-BLZ77-001','Lifestyle','Unisex',5800.00,'Leather','Casual','Street','Neutral','Low','Low',420.00,FALSE,'Vintage mid-top sneaker.'),
('Nike Air Max Plus','Nike','Air Max Plus','NK-AMP-001','Lifestyle','Men',8500.00,'Mesh','Casual','Street','Neutral','High','Medium',380.00,FALSE,'Tuned air distinctive design.'),
('Nike Cortez','Nike','Cortez','NK-CRTZ-001','Lifestyle','Women',5200.00,'Leather','Casual','Street','Neutral','Low','Low',310.00,FALSE,'Heritage running style.'),
('Nike Air Huarache','Nike','Air Huarache','NK-HRC-001','Lifestyle','Men',6800.00,'Neoprene/Leather','Casual','Street','Neutral','Medium','High',330.00,FALSE,'Foot hugging classic.'),
('Nike Tech Hera','Nike','Tech Hera','NK-THR-001','Lifestyle','Women',6200.00,'Textile','Casual','Street','Neutral','High','Medium',340.00,FALSE,'Chunky everyday style.'),
('Adidas Stan Smith','Adidas','Stan Smith','AD-STM-001','Lifestyle','Unisex',5500.00,'Synthetic','Casual','Street','Neutral','Low','Low',380.00,FALSE,'Clean classic tennis style.'),
('Adidas Superstar','Adidas','Superstar','AD-SPS-001','Lifestyle','Unisex',5500.00,'Leather','Casual','Street','Neutral','Low','Low',400.00,FALSE,'Shell toe classic sneaker.'),
('Adidas Gazelle','Adidas','Gazelle','AD-GZL-001','Lifestyle','Unisex',5200.00,'Suede','Casual','Street','Neutral','Low','Medium',360.00,FALSE,'Retro suede sneaker.'),
('Adidas Samba OG','Adidas','Samba OG','AD-SMB-001','Lifestyle','Unisex',6200.00,'Leather','Casual','Street','Neutral','Low','Low',350.00,FALSE,'Trending classic indoor football style.'),
('Adidas NMD_R1','Adidas','NMD_R1','AD-NMD1-001','Lifestyle','Men',7200.00,'Primeknit','Casual','Street','Neutral','Medium','High',290.00,FALSE,'Modern boost lifestyle shoe.'),
('Adidas Campus 00s','Adidas','Campus 00s','AD-CMP00-001','Lifestyle','Unisex',5800.00,'Suede','Casual','Street','Neutral','Low','Medium',400.00,FALSE,'Chunky skate inspired retro.'),
('Adidas Forum Low','Adidas','Forum Low','AD-FRM-001','Lifestyle','Unisex',5500.00,'Leather','Casual','Street','Neutral','Medium','Low',430.00,FALSE,'80s basketball lifestyle shoe.'),
('Adidas Ozelia','Adidas','Ozelia','AD-OZL-001','Lifestyle','Men',6500.00,'Textile','Casual','Street','Neutral','Medium','High',370.00,FALSE,'Futuristic chunky sneaker.'),
('New Balance 550','New Balance','550','NB-550-001','Lifestyle','Unisex',6800.00,'Leather','Casual','Street','Neutral','Medium','Low',420.00,FALSE,'Retro basketball lifestyle shoe.'),
('New Balance 2002R','New Balance','2002R','NB-2002R-001','Lifestyle','Men',7500.00,'Suede/Mesh','Casual','Street','Neutral','Medium','High',370.00,FALSE,'Y2K running style sneaker.'),
('New Balance 9060','New Balance','9060','NB-9060-001','Lifestyle','Unisex',8500.00,'Suede/Mesh','Casual','Street','Neutral','High','High',410.00,FALSE,'Chunky futuristic lifestyle shoe.'),
('New Balance 990v6','New Balance','990v6','NB-990V6-001','Lifestyle','Men',10500.00,'Suede/Mesh','Casual','Street','Stability','Medium','High',380.00,FALSE,'Made in USA premium sneaker.'),
('New Balance 327','New Balance','327','NB-327-001','Lifestyle','Women',5800.00,'Nylon/Suede','Casual','Street','Neutral','Medium','High',310.00,FALSE,'70s inspired retro runner.'),
('New Balance 574 Core','New Balance','574 Core','NB-574C-001','Lifestyle','Unisex',5500.00,'Suede/Mesh','Casual','Street','Neutral','Medium','High',340.00,FALSE,'The ultimate classic New Balance.'),
('Puma Suede Classic','Puma','Suede Classic','PM-SDC-001','Lifestyle','Unisex',4500.00,'Suede','Casual','Street','Neutral','Low','Medium',370.00,FALSE,'Timeless suede sneaker.'),
('Puma RS-X','Puma','RS-X','PM-RSX-001','Lifestyle','Unisex',5800.00,'Mesh/Synthetic','Casual','Street','Neutral','High','High',420.00,FALSE,'Chunky retro running style.'),
('Puma Cali','Puma','Cali','PM-CALI-001','Lifestyle','Women',4800.00,'Leather','Casual','Street','Neutral','Medium','Low',390.00,FALSE,'West coast inspired sneaker.'),
('Puma Rider FV','Puma','Rider FV','PM-RDFV-001','Lifestyle','Men',5200.00,'Nylon/Suede','Casual','Street','Neutral','Medium','High',350.00,FALSE,'Retro future lifestyle shoe.'),
('Skechers Uno Stand on Air','Skechers','Uno','SK-UNO-002','Lifestyle','Women',4500.00,'Synthetic','Casual','Street','Neutral','Medium','Medium',340.00,FALSE,'Air cushioned fashion sneaker.'),
('Skechers DLites','Skechers','DLites','SK-DLT-001','Lifestyle','Women',4800.00,'Leather/Mesh','Casual','Street','Neutral','High','High',380.00,FALSE,'The original chunky sneaker.'),
('Converse Chuck 70','Converse','Chuck 70','CV-C70-001','Lifestyle','Unisex',4500.00,'Canvas','Casual','Street','Neutral','Medium','High',410.00,FALSE,'Premium canvas high top.'),
('Converse Jack Purcell','Converse','Jack Purcell','CV-JP-001','Lifestyle','Unisex',4200.00,'Canvas','Casual','Street','Neutral','Low','High',390.00,FALSE,'Classic smile toe sneaker.'),
('Converse Run Star Hike','Converse','Run Star Hike','CV-RSH-001','Lifestyle','Unisex',6500.00,'Canvas','Casual','Street','Neutral','High','High',480.00,FALSE,'Platform chunky sole converse.'),
('Converse One Star','Converse','One Star','CV-OST-001','Lifestyle','Unisex',4600.00,'Suede','Casual','Street','Neutral','Low','Medium',400.00,FALSE,'Suede low top classic.'),
('Vans Old Skool','Vans','Old Skool','VN-OS-002','Lifestyle','Unisex',4200.00,'Canvas/Suede','Casual','Street','Neutral','Low','Medium',390.00,FALSE,'Iconic sidestripe skate shoe.'),
('Vans Slip-On','Vans','Slip-On','VN-SLP-001','Lifestyle','Unisex',3800.00,'Canvas','Casual','Street','Neutral','Low','High',350.00,FALSE,'Classic checkerboard slip on.'),
('Vans Sk8-Hi','Vans','Sk8-Hi','VN-SK8-001','Lifestyle','Unisex',4600.00,'Canvas/Suede','Casual','Street','Neutral','Low','Medium',420.00,FALSE,'High top skate classic.'),
('ASICS GEL-Lyte III','ASICS','GEL-Lyte III','AS-GL3-001','Lifestyle','Unisex',6500.00,'Suede/Mesh','Casual','Street','Neutral','Medium','High',340.00,FALSE,'Split tongue heritage sneaker.'),
('Reebok Club C 85','Reebok','Club C 85','RB-CC85-001','Lifestyle','Unisex',4800.00,'Leather','Casual','Street','Neutral','Low','Low',350.00,FALSE,'Vintage tennis lifestyle shoe.'),
('Onitsuka Tiger Mexico 66','Onitsuka Tiger','Mexico 66','OT-MEX66-001','Lifestyle','Unisex',6800.00,'Leather','Casual','Street','Neutral','Low','Low',290.00,FALSE,'Sleek heritage running shoe.'),
('Salomon XT-4','Salomon','XT-4','SL-XT4-001','Lifestyle','Unisex',9500.00,'Synthetic','Casual','Street','Stability','Medium','High',360.00,FALSE,'Trail style for the street.'),
('Nike Mercurial Superfly 9','Nike','Mercurial Superfly 9','NK-MS9-001','Football','Men',13500.00,'Synthetic','Firm Ground','Grass','Neutral','Low','High',195.00,FALSE,'Elite speed football boot.'),
('Nike Mercurial Vapor 15','Nike','Mercurial Vapor 15','NK-MV15-001','Football','Men',12800.00,'Synthetic','Firm Ground','Grass','Neutral','Low','High',185.00,FALSE,'Low cut speed boot.'),
('Nike Phantom GX','Nike','Phantom GX','NK-PGX-001','Football','Unisex',12500.00,'Gripknit','Firm Ground','Grass','Neutral','Low','High',205.00,FALSE,'Precision and control boot.'),
('Nike Phantom Luna','Nike','Phantom Luna','NK-PLU-001','Football','Women',12500.00,'Gripknit','Firm Ground','Grass','Neutral','Low','High',200.00,FALSE,'Female focused football boot.'),
('Nike Tiempo Legend 10','Nike','Tiempo Legend 10','NK-TL10-001','Football','Men',11500.00,'Synthetic Leather','Firm Ground','Grass','Neutral','Medium','High',230.00,FALSE,'Comfortable heritage boot.'),
('Nike Premier 3','Nike','Premier 3','NK-PRM3-001','Football','Men',6500.00,'K-Leather','Firm Ground','Grass','Neutral','Medium','Medium',245.00,FALSE,'Classic leather football boot.'),
('Adidas Predator Accuracy.1','Adidas','Predator Accuracy.1','AD-PRA1-001','Football','Men',12500.00,'HybridTouch','Firm Ground','Grass','Neutral','Low','High',225.00,FALSE,'Striking and control boot.'),
('Adidas X Crazyfast.1','Adidas','X Crazyfast.1','AD-XC1-001','Football','Men',12800.00,'Aeropacity','Firm Ground','Grass','Neutral','Low','High',180.00,FALSE,'Ultra lightweight speed boot.'),
('Adidas Copa Pure.1','Adidas','Copa Pure.1','AD-CP1-001','Football','Men',11500.00,'Leather','Firm Ground','Grass','Neutral','Medium','Medium',240.00,FALSE,'Premium leather touch boot.'),
('Adidas Goletto VIII','Adidas','Goletto VIII','AD-GOL8-001','Football','Men',3500.00,'Synthetic','Firm Ground','Grass','Neutral','Low','Low',260.00,FALSE,'Entry level firm ground boot.'),
('Adidas Predator Edge Kids','Adidas','Predator Edge','AD-PRED-001','Football','Kids',4500.00,'Synthetic','Firm Ground','Grass','Neutral','Low','Medium',210.00,FALSE,'Youth control football boot.'),
('Puma Future Ultimate','Puma','Future Ultimate','PM-FUT-001','Football','Men',11000.00,'Fuzionfit','Firm Ground','Grass','Neutral','Low','High',215.00,FALSE,'Agility and playmaker boot.'),
('Puma Ultra Ultimate','Puma','Ultra Ultimate','PM-ULT-001','Football','Men',11000.00,'Ultraweave','Firm Ground','Grass','Neutral','Low','High',185.00,FALSE,'Speed focused football boot.'),
('Puma King Ultimate','Puma','King Ultimate','PM-KNG-001','Football','Men',10500.00,'K-Better','Firm Ground','Grass','Neutral','Medium','Medium',230.00,FALSE,'Modernized heritage boot.'),
('Puma Attacanto','Puma','Attacanto','PM-ATT-001','Football','Men',3200.00,'Synthetic','Firm Ground','Grass','Neutral','Low','Low',255.00,FALSE,'Affordable durable football shoe.'),
('Mizuno Morelia Neo III','Mizuno','Morelia Neo III','MZ-MN3-001','Football','Men',14500.00,'K-Leather','Firm Ground','Grass','Neutral','Low','Medium',195.00,FALSE,'Made in Japan premium boot.'),
('Mizuno Alpha Japan','Mizuno','Alpha Japan','MZ-ALP-001','Football','Men',14800.00,'Synthetic','Firm Ground','Grass','Neutral','Low','High',190.00,FALSE,'Elite Japanese speed boot.'),
('New Balance Furon V7','New Balance','Furon V7','NB-FUR7-001','Football','Men',10800.00,'Hypoknit','Firm Ground','Grass','Neutral','Low','High',195.00,FALSE,'Explosive speed boot.'),
('New Balance Tekela V4','New Balance','Tekela V4','NB-TEK4-001','Football','Men',10800.00,'Knit','Firm Ground','Grass','Neutral','Low','High',210.00,FALSE,'Laceless control boot.'),
('Under Armour Magnetico','Under Armour','Clone Magnetico','UA-MAG-001','Football','Men',9500.00,'Clone','Firm Ground','Grass','Neutral','Medium','High',225.00,FALSE,'Adaptive fit football boot.'),
('ASICS DS Light','ASICS','DS Light','AS-DSL-001','Football','Men',7500.00,'K-Leather','Firm Ground','Grass','Neutral','Medium','Medium',220.00,FALSE,'Comfortable leather boot.'),
('Nike LeBron 21','Nike','LeBron 21','NK-LBJ21-001','Basketball','Men',11000.00,'Mesh/Leather','Game','Court','Stability','Maximum','High',400.00,FALSE,'King James flagship shoe.'),
('Nike KD 16','Nike','KD 16','NK-KD16-001','Basketball','Men',9500.00,'Mesh','Game','Court','Neutral','High','High',380.00,FALSE,'Kevin Durant versatile shoe.'),
('Nike Zoom Freak 5','Nike','Zoom Freak 5','NK-ZF5-001','Basketball','Men',7800.00,'Mesh','Game','Court','Neutral','Medium','High',360.00,FALSE,'Giannis signature basketball shoe.'),
('Nike Ja 1','Nike','Ja 1','NK-JA1-001','Basketball','Men',6800.00,'Mesh','Game','Court','Neutral','Medium','High',340.00,FALSE,'Lightweight bouncy signature shoe.'),
('Nike Tatum 1','Nike','Tatum 1','NK-TAT1-001','Basketball','Men',7200.00,'Mesh','Game','Court','Neutral','Medium','High',330.00,FALSE,'Ultra light basketball shoe.'),
('Nike Luka 2','Nike','Luka 2','NK-LUK2-001','Basketball','Men',7500.00,'Synthetic/Mesh','Game','Court','Stability','Medium','High',390.00,FALSE,'Step-back focused control shoe.'),
('Nike GT Cut 2','Nike','GT Cut 2','NK-GTC2-001','Basketball','Men',8500.00,'Mesh','Game','Court','Neutral','High','High',360.00,FALSE,'Designed for fast cuts and speed.'),
('Adidas Trae Young 3','Adidas','Trae Young 3','AD-TY3-001','Basketball','Men',8200.00,'Knit','Game','Court','Neutral','Medium','High',370.00,FALSE,'Agility and speed basketball shoe.'),
('Adidas AE 1','Adidas','AE 1','AD-AE1-001','Basketball','Men',7500.00,'Synthetic','Game','Court','Stability','High','High',410.00,FALSE,'Anthony Edwards signature shoe.'),
('Adidas Harden Vol 7','Adidas','Harden Vol 7','AD-HRD7-001','Basketball','Men',9200.00,'Textile','Game','Court','Stability','High','Medium',420.00,FALSE,'James Harden signature shoe.'),
('Adidas DON Issue 5','Adidas','DON Issue 5','AD-DON5-001','Basketball','Men',6800.00,'Mesh','Game','Court','Neutral','Medium','High',380.00,FALSE,'Donovan Mitchell signature shoe.'),
('Adidas Dame 8','Adidas','Dame 8','AD-DAM8-001','Basketball','Men',7500.00,'Mesh','Game','Court','Neutral','High','High',390.00,FALSE,'Damian Lillard signature shoe.'),
('Under Armour Curry 11','Under Armour','Curry 11','UA-CUR11-001','Basketball','Men',9500.00,'Knit','Game','Court','Neutral','Medium','High',350.00,FALSE,'Stephen Curry signature shoe.'),
('Under Armour Spawn 5','Under Armour','Spawn 5','UA-SPW5-001','Basketball','Men',6200.00,'Mesh','Game','Court','Neutral','Medium','High',360.00,FALSE,'Anatomical design basketball shoe.'),
('Puma MB.03','Puma','MB.03','PM-MB03-001','Basketball','Men',8500.00,'Mesh','Game','Court','Neutral','Medium','High',390.00,FALSE,'LaMelo Ball signature shoe.'),
('Puma All-Pro Nitro','Puma','All-Pro Nitro','PM-APN-001','Basketball','Men',7500.00,'Mesh','Game','Court','Neutral','High','High',380.00,FALSE,'Responsive nitro foam basketball shoe.'),
('Puma Scoot Zeros','Puma','Scoot Zeros','PM-SCZ-001','Basketball','Men',6500.00,'Mesh','Game','Court','Neutral','Medium','High',370.00,FALSE,'Scoot Henderson signature shoe.'),
('New Balance Two WXY V4','New Balance','Two WXY V4','NB-TW4-001','Basketball','Men',7800.00,'Mesh','Game','Court','Neutral','High','High',380.00,FALSE,'Positionless basketball shoe.'),
('New Balance Kawhi III','New Balance','Kawhi III','NB-KAW3-001','Basketball','Men',9200.00,'Synthetic','Game','Court','Stability','Medium','Medium',400.00,FALSE,'Kawhi Leonard signature shoe.'),
('Converse All Star BB Trilliant','Converse','BB Trilliant','CV-BBT-001','Basketball','Men',7200.00,'Mesh','Game','Court','Neutral','Medium','High',360.00,FALSE,'Responsive modern converse hoops shoe.'),
('Nike Zoom Vapor Pro 2','Nike','Vapor Pro 2','NK-ZVP2-001','Tennis','Men',7200.00,'Mesh','Match','Court','Neutral','Medium','High',360.00,FALSE,'Lightweight speed tennis shoe.'),
('Nike Zoom Vapor Cage 4','Nike','Vapor Cage 4','NK-ZVC4-001','Tennis','Men',8500.00,'Synthetic','Match','Court','Stability','High','Medium',410.00,FALSE,'Durable hard court tennis shoe.'),
('Nike Court Air Zoom NXT','Nike','Court NXT','NK-CNXT-001','Tennis','Women',7500.00,'Mesh','Match','Court','Neutral','High','High',340.00,FALSE,'Bouncy match day shoe.'),
('Adidas Barricade','Adidas','Barricade','AD-BAR-001','Tennis','Men',8200.00,'Mesh','Match','Court','Stability','High','High',400.00,FALSE,'Ultimate stability tennis shoe.'),
('Adidas Ubersonic 4','Adidas','Ubersonic 4','AD-UBS4-001','Tennis','Women',7500.00,'Primeknit','Match','Court','Neutral','Medium','High',340.00,FALSE,'Lightweight responsive tennis shoe.'),
('Adidas Defiant Speed','Adidas','Defiant Speed','AD-DEF-001','Tennis','Men',5800.00,'Mesh','Match','Court','Neutral','Medium','High',350.00,FALSE,'Fast affordable tennis shoe.'),
('ASICS Gel-Resolution 9','ASICS','Gel-Resolution 9','AS-RES9-001','Tennis','Men',8500.00,'PU/Mesh','Match','Court','Stability','High','Medium',400.00,FALSE,'Premium baseline stability shoe.'),
('ASICS Court FF 3','ASICS','Court FF 3','AS-CFF3-002','Tennis','Men',9500.00,'PU/Mesh','Match','Court','Stability','High','Medium',415.00,FALSE,'Novak Djokovic signature shoe.'),
('ASICS Solution Speed FF 2','ASICS','Solution Speed FF 2','AS-SSF2-001','Tennis','Women',7900.00,'Mesh','Match','Court','Neutral','Medium','High',310.00,FALSE,'Ultra light speed tennis shoe.'),
('New Balance Coco CG1','New Balance','Coco CG1','NB-CG1-001','Tennis','Women',9200.00,'Synthetic','Match','Court','Stability','Medium','Medium',390.00,FALSE,'Coco Gauff signature shoe.'),
('New Balance CT302','New Balance','CT302','NB-CT302-001','Tennis','Women',5800.00,'Leather','Casual','Court','Neutral','Medium','Low',420.00,FALSE,'Platform lifestyle tennis shoe.'),
('New Balance 996v5','New Balance','996v5','NB-996V5-001','Tennis','Men',7200.00,'Knit','Match','Court','Neutral','Medium','High',355.00,FALSE,'Comfortable flexible match shoe.'),
('K-Swiss Hypercourt Express 2','K-Swiss','Hypercourt Express 2','KS-HYP2-001','Tennis','Men',6500.00,'Mesh/PU','Match','Court','Neutral','Medium','High',380.00,FALSE,'Comfortable wide fit tennis shoe.'),
('Wilson Rush Pro 4.0','Wilson','Rush Pro 4.0','WL-RP4-001','Tennis','Men',7800.00,'Mesh','Match','Court','Stability','High','High',395.00,FALSE,'Dynamic court movement shoe.'),
('Babolat Propulse Fury 3','Babolat','Propulse Fury 3','BB-PF3-001','Tennis','Men',8200.00,'Synthetic','Match','Court','Stability','High','Medium',405.00,FALSE,'Maximum durability and support.'),
('Nike SB Dunk Low','Nike','SB Dunk Low','NK-SBDL-001','Skateboarding','Unisex',7500.00,'Leather/Suede','Skate','Street','Neutral','Medium','Low',410.00,FALSE,'Iconic padded skate shoe.'),
('Nike SB Nyjah 3','Nike','Nyjah 3','NK-NYJ3-001','Skateboarding','Men',6200.00,'Rubber/Mesh','Skate','Street','Neutral','Medium','High',360.00,FALSE,'Technical durable skate shoe.'),
('Nike SB Ishod','Nike','Ishod','NK-ISH-001','Skateboarding','Men',6500.00,'Suede','Skate','Street','Neutral','Low','Medium',380.00,FALSE,'Ishod Wair signature shoe.'),
('Nike SB Blazer Mid','Nike','SB Blazer Mid','NK-SBBM-001','Skateboarding','Unisex',5800.00,'Suede','Skate','Street','Stability','Medium','Low',430.00,FALSE,'Classic mid top skate shoe.'),
('Adidas Busenitz','Adidas','Busenitz','AD-BSN-001','Skateboarding','Men',5500.00,'Suede','Skate','Street','Neutral','Low','Medium',390.00,FALSE,'Football inspired skate shoe.'),
('Adidas Tyshawn','Adidas','Tyshawn','AD-TYS-001','Skateboarding','Men',5800.00,'Leather','Skate','Street','Stability','Medium','Low',420.00,FALSE,'Mid top skate shoe.'),
('Adidas Matchbreak Super','Adidas','Matchbreak','AD-MBS-001','Skateboarding','Unisex',4800.00,'Canvas/Suede','Skate','Street','Neutral','Low','Medium',370.00,FALSE,'Vulcanized smooth skate shoe.'),
('Vans Half Cab','Vans','Half Cab','VN-HC-001','Skateboarding','Unisex',5200.00,'Suede','Skate','Street','Stability','Medium','Low',410.00,FALSE,'Steve Caballero signature shoe.'),
('Vans Kyle Walker','Vans','Kyle Walker','VN-KW-001','Skateboarding','Men',5500.00,'Suede','Skate','Street','Neutral','Medium','Medium',400.00,FALSE,'Wafflecup skate shoe.'),
('Vans Authentic Pro','Vans','Authentic Pro','VN-AUTHP-001','Skateboarding','Unisex',4500.00,'Canvas','Skate','Street','Neutral','Low','High',360.00,FALSE,'Pro upgraded authentic.'),
('Vans Rowan 2','Vans','Rowan 2','VN-ROW2-001','Skateboarding','Men',5800.00,'Suede/Mesh','Skate','Street','Stability','High','Medium',415.00,FALSE,'Impact absorbing skate shoe.'),
('Converse One Star Pro','Converse','One Star Pro','CV-OSP-001','Skateboarding','Unisex',4800.00,'Suede','Skate','Street','Neutral','Low','Medium',390.00,FALSE,'Skate upgraded classic.'),
('Converse CTAS Pro Hi','Converse','CTAS Pro Hi','CV-CTAS-001','Skateboarding','Unisex',5200.00,'Suede','Skate','Street','Neutral','Medium','Medium',420.00,FALSE,'Skate ready high top.'),
('New Balance Numeric 272','New Balance','Numeric 272','NB-NM272-001','Skateboarding','Men',4900.00,'Suede/Canvas','Skate','Street','Neutral','Low','High',380.00,FALSE,'Vulcanized board feel shoe.'),
('New Balance Numeric 440','New Balance','Numeric 440','NB-NM440-001','Skateboarding','Unisex',5200.00,'Suede/Mesh','Skate','Street','Neutral','Medium','Medium',390.00,FALSE,'Cupsole retro skate shoe.'),
('Nike Pegasus Trail 4','Nike','Pegasus Trail 4','NK-PT4-001','Trail Running','Men',7500.00,'Mesh','Trail Running','Trail','Neutral','Medium','High',290.00,FALSE,'Road to trail hybrid shoe.'),
('Nike Wildhorse 8','Nike','Wildhorse 8','NK-WH8-001','Trail Running','Women',7200.00,'Mesh','Trail Running','Trail','Neutral','Medium','High',300.00,FALSE,'Rugged trail running shoe.'),
('Nike Zegama','Nike','Zegama','NK-ZEG-001','Trail Running','Men',8500.00,'Mesh','Trail Running','Trail','Neutral','High','High',315.00,FALSE,'Deep lugs for technical trails.'),
('Adidas Terrex Speed Ultra','Adidas','Speed Ultra','AD-TSU-001','Trail Running','Men',9500.00,'Mesh','Trail Racing','Trail','Neutral','Medium','High',245.00,FALSE,'Fast lightweight trail racer.'),
('Adidas Terrex Agravic Flow 2','Adidas','Agravic Flow 2','AD-TAF2-001','Trail Running','Women',7200.00,'Mesh','Trail Running','Trail','Neutral','Medium','High',295.00,FALSE,'Versatile off road shoe.'),
('ASICS Trabuco Max 2','ASICS','Trabuco Max 2','AS-TRB2-001','Trail Running','Men',7800.00,'Mesh','Trail Running','Trail','Neutral','Maximum','High',305.00,FALSE,'Max cushion trail runner.'),
('ASICS Gel-Trabuco 11','ASICS','Gel-Trabuco 11','AS-GTR11-001','Trail Running','Women',7200.00,'Mesh','Trail Running','Trail','Stability','Medium','High',285.00,FALSE,'Stable protective trail shoe.'),
('HOKA Speedgoat 5','HOKA','Speedgoat 5','HK-SG5-001','Trail Running','Unisex',8500.00,'Jacquard Mesh','Trail Running','Trail','Neutral','High','High',291.00,FALSE,'Grippy technical trail shoe.'),
('HOKA Mafate Speed 4','HOKA','Mafate Speed 4','HK-MS4-001','Trail Running','Men',9200.00,'Mesh','Trail Running','Trail','Neutral','High','High',295.00,FALSE,'Responsive technical trail shoe.'),
('HOKA Challenger 7','HOKA','Challenger 7','HK-CHL7-001','Trail Running','Women',7500.00,'Mesh','Trail Running','Trail','Neutral','High','High',252.00,FALSE,'All terrain hybrid shoe.'),
('Salomon Speedcross 6','Salomon','Speedcross 6','SL-SC6-001','Trail Running','Men',8800.00,'Ripstop','Trail Running','Mud','Neutral','Medium','Medium',298.00,FALSE,'Aggressive grip for mud.'),
('Salomon Sense Ride 5','Salomon','Sense Ride 5','SL-SR5-001','Trail Running','Women',7500.00,'Mesh','Trail Running','Trail','Neutral','Medium','High',286.00,FALSE,'Versatile all around trail shoe.'),
('Salomon Ultra Glide 2','Salomon','Ultra Glide 2','SL-UG2-001','Trail Running','Men',8200.00,'Mesh','Long Distance','Trail','Neutral','Maximum','High',260.00,FALSE,'Max cushion long distance trail.'),
('Brooks Cascadia 17','Brooks','Cascadia 17','BK-CAS17-001','Trail Running','Men',7800.00,'Mesh','Trail Running','Trail','Stability','Medium','High',311.00,FALSE,'Stable protective trail shoe.'),
('New Balance Hierro V7','New Balance','Hierro V7','NB-HRO7-001','Trail Running','Men',7500.00,'Mesh','Trail Running','Trail','Neutral','High','High',300.00,FALSE,'Cushioned vibram trail shoe.'),
('Salomon X Ultra 4 GTX','Salomon','X Ultra 4 GTX','SL-XU4-001','Hiking','Men',9500.00,'Synthetic','Hiking','Trail','Stability','Medium','Low',390.00,TRUE,'Agile waterproof hiker.'),
('Salomon Quest 4 GTX','Salomon','Quest 4 GTX','SL-QST4-001','Hiking','Men',12500.00,'Nubuck','Backpacking','Trail','Maximum','High','Low',655.00,TRUE,'Heavy duty backpacking boot.'),
('Merrell Moab 3 GTX','Merrell','Moab 3 GTX','MR-MO3-001','Hiking','Men',7800.00,'Leather/Mesh','Hiking','Trail','Stability','Medium','Medium',460.00,TRUE,'Mother of all boots.'),
('Merrell Rogue Hiker','Merrell','Rogue Hiker','MR-RGH-001','Hiking','Men',11000.00,'Ballistic Mesh','Backpacking','Trail','Stability','High','Medium',530.00,TRUE,'Lightweight backpacking boot.'),
('Columbia Newton Ridge','Columbia','Newton Ridge Plus','CL-NWT-001','Hiking','Women',6500.00,'Leather/Mesh','Hiking','Trail','Stability','Medium','Medium',410.00,TRUE,'Classic waterproof hiking boot.'),
('Columbia Facet 75','Columbia','Facet 75 Alpha','CL-FCT-001','Hiking','Men',7200.00,'Mesh','Fast Hiking','Trail','Neutral','High','High',400.00,TRUE,'Modern sneaker like hiker.'),
('Adidas Terrex Free Hiker 2','Adidas','Free Hiker 2','AD-TFH2-001','Hiking','Men',11500.00,'Primeknit','Hiking','Trail','Neutral','Maximum','High',445.00,TRUE,'Boost cushioned hiking boot.'),
('Adidas Terrex Swift R3','Adidas','Swift R3','AD-TSR3-001','Hiking','Women',8500.00,'Synthetic','Hiking','Trail','Stability','Medium','Medium',395.00,TRUE,'Fast and rugged hiking shoe.'),
('HOKA Kaha 2 GTX','HOKA','Kaha 2 GTX','HK-KAH2-001','Hiking','Women',11800.00,'Nubuck','Backpacking','Trail','Stability','Maximum','Medium',476.00,TRUE,'Plush waterproof hiking boot.'),
('HOKA Anacapa Mid GTX','HOKA','Anacapa Mid','HK-ANA-001','Hiking','Men',9200.00,'Leather/Mesh','Hiking','Trail','Neutral','High','Medium',453.00,TRUE,'Sustainable leather day hiker.'),
('Timberland Mt Maddsen','Timberland','Mt Maddsen','TB-MTM-001','Hiking','Men',7500.00,'Leather','Hiking','Trail','Stability','Medium','Low',500.00,TRUE,'Classic leather hiking boot.'),
('Keen Targhee III','Keen','Targhee III','KN-TRG3-001','Hiking','Men',8200.00,'Leather','Hiking','Trail','Stability','Medium','Medium',490.00,TRUE,'Roomy toe box hiker.'),
('Oboz Bridger Mid BDry','Oboz','Bridger Mid','OB-BRG-001','Hiking','Women',9500.00,'Leather','Backpacking','Trail','Maximum','Medium','Low',460.00,TRUE,'Supportive waterproof boot.'),
('Lowa Renegade GTX Mid','Lowa','Renegade GTX','LW-RNG-001','Hiking','Men',12800.00,'Nubuck','Hiking','Trail','Stability','Medium','Low',550.00,TRUE,'Legendary premium hiking boot.'),
('La Sportiva Ultra Raptor II','La Sportiva','Ultra Raptor II','LS-UR2-001','Hiking','Men',9200.00,'Mesh','Fast Hiking','Trail','Stability','Medium','High',400.00,FALSE,'Mountain running inspired hiker.'),
('Nike Air Force 1 Kids','Nike','Air Force 1','NK-AF1K-001','Kids','Boys',3500.00,'Leather','Casual','Street','Neutral','Medium','Low',310.00,FALSE,'Classic AF1 for kids.'),
('Adidas Grand Court Kids','Adidas','Grand Court','AD-GCK-001','Kids','Unisex',2800.00,'Synthetic','Casual','Street','Neutral','Low','Low',250.00,FALSE,'Tennis style kids shoe.'),
('Puma Smash v2 Kids','Puma','Smash v2','PM-SMK-001','Kids','Girls',2500.00,'Synthetic','Casual','Street','Neutral','Low','Low',220.00,FALSE,'Everyday kids sneaker.'),
('Skechers Twinkle Toes','Skechers','Twinkle Toes','SK-TWN-001','Kids','Girls',3200.00,'Canvas','Casual','Street','Neutral','Low','High',240.00,FALSE,'Light up casual shoe.'),
('Vans Old Skool Kids','Vans','Old Skool','VN-OSK-001','Kids','Unisex',2900.00,'Canvas','Casual','Street','Neutral','Low','Medium',260.00,FALSE,'Classic skate shoe for kids.'),
('New Balance 574 Kids','New Balance','574','NB-574K-001','Kids','Boys',3200.00,'Suede/Mesh','Casual','Street','Neutral','Medium','High',240.00,FALSE,'Classic NB style for kids.'),
('ASICS Contend 8 Kids','ASICS','Contend 8','AS-CON8-001','Kids','Unisex',2800.00,'Mesh','Running','Road','Neutral','Medium','High',210.00,FALSE,'Durable kids running shoe.'),
('Under Armour Assert 10 Kids','Under Armour','Assert 10','UA-AST10-001','Kids','Boys',2900.00,'Mesh','Running','Road','Neutral','Medium','High',220.00,FALSE,'Breathable active kids shoe.'),
('Nike Dynamo Go Kids','Nike','Dynamo Go','NK-DYN-001','Kids','Unisex',3400.00,'Foam/Textile','Casual','Street','Neutral','Medium','High',180.00,FALSE,'Easy slip on kids shoe.'),
('Adidas Duramo Kids','Adidas','Duramo','AD-DURK-001','Kids','Girls',2700.00,'Mesh','Running','Road','Neutral','Medium','High',200.00,FALSE,'Lightweight kids active shoe.'),
('Crocs Classic Clog','Crocs','Classic Clog','CR-CLA-001','Sandals','Unisex',2500.00,'Croslite','Casual','Mixed','Neutral','Medium','High',170.00,TRUE,'The iconic comfortable clog.'),
('Birkenstock Arizona','Birkenstock','Arizona','BK-ARZ-001','Sandals','Unisex',5500.00,'Birko-Flor','Casual','Street','Arch Support','Firm','High',250.00,FALSE,'Classic cork footbed sandal.'),
('Nike Victori One','Nike','Victori One','NK-VIC-001','Sandals','Men',1800.00,'Synthetic','Recovery','Street','Neutral','Soft','High',150.00,TRUE,'Comfortable shower slide.'),
('Adidas Adilette Comfort','Adidas','Adilette Comfort','AD-ADI-001','Sandals','Women',2000.00,'Synthetic','Recovery','Street','Neutral','Soft','High',160.00,TRUE,'Plush footbed slide.'),
('Teva Hurricane XLT2','Teva','Hurricane XLT2','TV-HUR-001','Sandals','Unisex',3800.00,'Webbing','Outdoor','Trail','Neutral','Medium','High',290.00,TRUE,'Rugged outdoor sport sandal.'),
('Timberland 6-Inch Premium','Timberland','6-Inch Premium','TB-6IN-001','Boots','Men',11000.00,'Nubuck','Lifestyle','Mixed','Stability','Medium','Low',800.00,TRUE,'The original yellow boot.'),
('Dr Martens 1460','Dr. Martens','1460','DM-1460-001','Boots','Unisex',9500.00,'Leather','Lifestyle','Street','Neutral','Firm','Low',750.00,FALSE,'Classic 8-eye combat boot.'),
('Caterpillar Colorado','Caterpillar','Colorado','CAT-COL-001','Boots','Men',7800.00,'Leather','Lifestyle','Mixed','Stability','Firm','Low',850.00,FALSE,'Rugged workwear lifestyle boot.'),
('Blundstone 585','Blundstone','585 Classic','BL-585-001','Boots','Unisex',10500.00,'Leather','Lifestyle','Mixed','Neutral','Medium','Low',500.00,TRUE,'Chelsea boot with rustic finish.'),
('UGG Classic Short','UGG','Classic Short','UG-CLS-001','Boots','Women',8500.00,'Sheepskin','Casual','Street','Neutral','Soft','Low',350.00,FALSE,'Warm sheepskin winter boot.');